### ISSUE TITLE
咨询个问题：为什么goim没有基于gopush-cluster做呢？

### ISSUE THREAD

**Issue by liudanking** [Terry-Mao/goim#10]
从功能上看，把gopush-cluster的client上行协议扩展一下，然后comet通过rpc到web，就可以实现用户A和用户B双向通信了。
群组这些功能在管道上面做在业务逻辑层里面就可以了。
还可以避免在goim里面再定义一套私有协议。
请问从头开始写goim的原因是什么呢？

**Comment by Terry-Mao** [comment]
因为整体架构有点不同，之前gopush-cluster考虑更多是单IDC的集群实现，现在goim 只考虑comet是负责message dispatch（消息转发），意思就是多个IDC可以接入comet，然后再转发给router，做路由注册，从实现上有点不同，而且goim对消息的收发做了高度的优化

**Comment by liudanking** [comment]
这样的话，router就是所有消息的中心了，需要保存所有各个comet上在线用户的comet地址和session，感觉不容易横向扩展。之前gopush-cluster用一致性hash就不存在这个问题

**Comment by Terry-Mao** [comment]
router 模块估算了一下即使是一亿在线，也没多少量，扩展可以做的，连接到router时候，内部可以拆分。目前腾讯其实是所有IDC router 全局同步的，这样各个IDC甚至可以直连本IDC的router模块查询
