### ISSUE TITLE
无法运行websocket tls的client

### ISSUE THREAD

**Issue by eric-hon** [Terry-Mao/goim#107]
在client.conf中修改type 为 2，修改cert.file 为 ./cert.pem，拷贝自带的cert.pem到bin目录下，然后运行，无法运行：
eric@go:~/go/bin$ ./client 1 5000 localhost:8090
[06/20/16 17:28:48] [INFO] ===================WEBSOCKETS!
eric@go:~/go/bin$ ./client 1 5000 localhost:8080
[06/20/16 17:28:55] [INFO] ===================WEBSOCKETS!
上面的提示信息是我在入口的地方添加的，除此之外没有任何提示信息

**Comment by liutaihua** [comment]
关于wss的部分， 我建议是用nginx在前面做代理的， ssl放在nginx上。
goim就ws就行了， 测好ws， 然后挂ngx后面就好了。

**Comment by Terry-Mao** [comment]
@thinkboy

**Comment by thinkboy** [comment]
那个启动命令是benchmark下的client的启动方式。不是comet目录下的。comet下的client启动参数是 -c client.conf
