### ISSUE TITLE
ws测试例子,为什么在send里面发送消息body带着，onmessage收不到body里面的字符串

### ISSUE THREAD

**Issue by eric-hon** [Terry-Mao/goim#115]
ws测试例子,为什么在send里面发送消息body带着，onmessage查看body却是空的
function heartbeat() {
                ws.send(JSON.stringify({
                    'ver': 1,
                    'op': 2,
                    'seq': 2,
                    'body': {'ok':'123456'}
                }));
            }
所以，请问一下，如何测试接受消息？

**Comment by liutaihua** [comment]
op: 2是一个心跳包，心跳包回复的时候， body被comet置空了。
如果对心跳包还有其他附带逻辑，需要自己稍微修改下回复。

**Comment by eric-hon** [comment]
op的定义在哪，怎么没看到，1234567890这些定义是什么？

**Comment by im-qq** [comment]
op定义在libs/define里面的operation.go，op=2是心跳，op=4是发送消息，不过ws的write packet目前还存在点问题。

**Comment by eric-hon** [comment]
我修改了，但server挂了。你能发一个可以发送和接收消息的ws例子吗？
谢谢！

**Comment by eric-hon** [comment]
增加个定时器，但一运行，commet就挂掉。
function test(){
				ws.send(JSON.stringify({
					'ver': 1,
                    'op': 4,
                    'seq': 1001,
                    'body': {'data':'hello world!'}
				}));
			}

还请你发一个可以发送和接收消息的ws例子吗？
谢谢！

**Comment by eric-hon** [comment]
请问，如何接收呢？

**Comment by im-qq** [comment]
晚点有时间我看看，先修复一下。

**Comment by eric-hon** [comment]
使用curl -d "{\"test\":1}" http://127.0.0.1:7172/1/push?uid=0发送消息，
ws测试例子client接收不到消息？？？

**Comment by linminglu** [comment]
我个人感觉他都没去看代码
