### ISSUE TITLE
使用curl -d "{\"test\":1}" http://127.0.0.1:7172/1/push?uid=0，只能使用uid=0,如果换成其他的数字，java sdk无法收到消息

### ISSUE THREAD

**Issue by eric-hon** [Terry-Mao/goim#116]
使用curl -d "{\"test\":1}" http://127.0.0.1:7172/1/push?uid=0，只能使用uid=0,如果换成其他的数字，java sdk无法收到消息
为什么？

**Comment by eric-hon** [comment]
这个怎么解决？

**Comment by liutaihua** [comment]
这个描述上下文不足。
uid是logic里的Auth分配的，或者你自己实现其他auth方式。
如果你jdk的uid是未知的， 你发消息肯定是发不到它上面去的。

你可以把你的场景描述详细点

**Comment by eric-hon** [comment]
curl -d "{\"test\":1}" http://127.0.0.1:7172/1/push?uid=0，把uid改成其他数字，比如10，6108等等，发送消息。
然后在java sdk修改
PushClient cb = new PushClient(InetAddress.getByName("192.168.20.244"), 8080 , 6108, "game");
运行，
无法接收消息

**Comment by eric-hon** [comment]
如果curl -d "{\"test\":1}" http://127.0.0.1:7172/1/push?uid=0,uid不做修改，保持为0，java sdk中的uid改成任何数字都可以接收消息

**Comment by eric-hon** [comment]
java sdk就是goim项目中提供的那个

**Comment by eric-hon** [comment]
能帮忙解决下为什么只有 uid=0,sdk才能接收消息？

**Comment by liutaihua** [comment]
你得看看 logic/auth.go里面的Auth方法， 如果你没改过的话。
如果你连接comet的时候，没提供对应的用于auth的body内容，那默认是uid总是0， 不知道你java里连comet的地方是怎么写的。

**Comment by eric-hon** [comment]
你那有连接的例子吗？发个看看，谢谢！

**Comment by eric-hon** [comment]
搞定了，呵呵，后面哥有时间就对该项目进行改善
