### ISSUE TITLE
在有心跳的情况下，发送端过个十几分钟发消息，但接收端没收到，再发信息就能收到了，是这样的吗

### ISSUE THREAD

**Issue by eric-hon** [Terry-Mao/goim#118]
在有心跳的情况下，发送端过个十几分钟发消息，但接收端没收到，再发信息就能收到了，即第一条信息丢失了，是这样的吗？

**Comment by chenxijunlove** [comment]
我也发现有这个问题

**Comment by sonwa** [comment]
同样发现这个问题，这个解决了了吗？

**Comment by im-qq** [comment]
最新PR有修复这个问题，添加kakfa ack后可以触发kafka broker重连后发送消息。

**Comment by Terry-Mao** [comment]
已经合并到develop分支
