### ISSUE TITLE
goim使用中的一个疑惑

### ISSUE THREAD

**Issue by jie123108** [Terry-Mao/goim#126]
goim现在的架构图里面，只有从后台往客户端推送消息。如果我希望客户端也同时能发送各种消息（to: 个人，多人，房间)。需要怎么做？
我目前想到的，可能有以下几种方式：
1：通过自己服务器的http接口，发送，然后服务器通过goim的http的push接口来发送。
2：通过客户端的websocket，发送，然后在comet中处理，并通过goim的http的push接口来发送。
想请教一下，哪种方式更好，或者有没有更合适的方式？

另外：第2种方式中，在comet中，是否可以直接通过RPC来通讯？我看comet中的RPC，看起来像是和logic通讯的，不知道理解的对不对。

**Comment by jie123108** [comment]
已经通过其它方式，咨询了毛老大，准备采取建议，直接采用第一种方式，走自己的HTTP接口。

**Comment by kunshao753** [comment]
请问第二种方式哪里有不妥吗？

**Comment by tonyboxes** [comment]
第二种方式对开发比较麻烦一些，包括消息发送状态回执，一般发送消息量不太多，走http方式会简单很多
