### ISSUE TITLE
Some libs import path should add "github.com" prefix

### ISSUE THREAD

**Issue by it-man-cn** [Terry-Mao/goim#130]
Trunk code does not compile correctly. Some libs import path should add "github.com" prefix.
such as:
https://github.com/Terry-Mao/goim/blob/master/comet/rpc.go
import (
	inet "goim/libs/net"  // inet "github.com/goim/libs/net"
	"goim/libs/proto"
	"net"
	"net/rpc"

	log "github.com/thinkboy/log4go"
)

**Comment by im-qq** [comment]
$ cd $GOPATH/src
$ git clone https://github.com/Terry-Mao/goim.git
$ cd $GOPATH/src/goim

Need to clone project to the src directory.
