### ISSUE TITLE
comet开起来的时候内存就500M，我用你的测试程序开一个客户端，每秒发一条消息，内存也一直在涨，没有停过

### ISSUE THREAD

**Issue by zwdsl** [Terry-Mao/goim#131]
comet开起来的时候内存就500M，我用你的测试程序开一个客户端，每秒发一条消息，内存也一直在涨，没有停过。请问是正常的吗

**Comment by liutaihua** [comment]
正常的， 另外也不会一直增，除非你连接真的是海量。
另外看你用的是tcp还是websocket， ws的连接新开的内存会在连接断开后被gc释放，不过这需要时间和gc的心情 ：)
tcp方式用了内存池， 内存池没有缩减逻辑，只有增加， 不过也是限于你连接很多内存池不够用了，才会新开一次内存。

你要初始就很小， 那把comet.conf里tcp的writer, reader都设小一点。

**Comment by im-qq** [comment]
目前看各个模块内存还是比较稳定的，只是job模块有微微涨应该有内存泄漏，正在抽时间查查这问题。 @liutaihua 你们那边job模块内存稳定不呢

**Comment by liutaihua** [comment]
@im-qq 我这job也有点泄露。因为比较微弱，暂时也没去看 ＝。＝

**Comment by imroc** [comment]
@liutaihua 我也是comet内存占太多以至于一般都启动不了,即使启动了服务器也卡的不能正常工作,改下comet.conf的reader和writer配置就搞定了
