### ISSUE TITLE
架构疑问

### ISSUE THREAD

**Issue by kirk91** [Terry-Mao/goim#134]
- 发送消息被强制拆成两步, 首先在 `logic` 中查询 `user` 与 `comet server` 的mapping, 然后把 `message` 发送到 `mq` 消息中间件, 接着 `job` 消费 `message` 并向指定的 `comet` 发送消息，一个逻辑上 事务被拆分成两个部分，这样拆分的考虑是? 如果获取到mapping后，客户端重连到了另外一个网关，发送到 `kafka` 中的消息便无效了, 整个事务放在 `job`中是不是更好一点?

- `kafka` 消息队列中间件在整个架构中，承担了的角色是？起到的作用是? 消峰、异步?

@Terry-Mao @im-qq

**Comment by thinkboy** [comment]
对于推送着的消息可以很快的记录下来，转发可以慢慢转。队列起到异步作用，并且不阻塞发送消息。

**Comment by Terry-Mao** [comment]
这样，核心逻辑在job，可以随时重启，不丢失消息。Kafka起到异步、消峰、排队、负载均衡（多partition）、以及消息持久化延迟发送；

**Comment by kirk91** [comment]
嗯，核心逻辑在`job`? job 当前除了消息的消费分发，貌似没有其他的逻辑, 核心应该是在logic吧. 另外`job` 当前的设计是可能会丢消息的, 从`kafka`中取消息后，放在了内部的channel中的, 然后就 `commit` 了, 在svr重启或crash是会丢失一部分的.

**Comment by Terry-Mao** [comment]
job有聚合消息逻辑，会依赖comet，logic 主要是转发。
这部分的job重启确实会丢，但是不希望调用logic全部失败了

**Comment by Terry-Mao** [comment]
@kirk91 可以根据自己喜欢去掉Kafka或者直接通讯

**Comment by kirk91** [comment]
👌，多谢 😄
