### ISSUE TITLE
关于demo收发问题

### ISSUE THREAD

**Issue by sonwa** [Terry-Mao/goim#137]
hi，看iOS demo只人认证和心跳包。指教一下怎么可以收发信息的呀？
发[socketServe sendMessage:@"hello world"]没反应喔。

**Comment by linminglu** [comment]
连接就断开了。 你这个发送方式也不对

**Comment by im-qq** [comment]
后端需要处理对应接收消息的op，operation.go

**Comment by sonwa** [comment]
连接没断开，用“curl -d "{\"test\": 1}" http://127.0.0.1:7172/1/push/all” 发送是可以收到。


接收消息要改后端operation.go。有没详细的文档参考下的？

**Comment by im-qq** [comment]
这块可以看看自己的需求，修改operation.go处理逻辑就可以了。
