### ISSUE TITLE
调用http://ip:7172/1/push/all example中的websocket接受不到消息

### ISSUE THREAD

**Issue by wangzhengnan** [Terry-Mao/goim#142]
如题：
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic KafkaPushsTopic --from-beginning
kafka可以收到消息

**Comment by wangzhengnan** [comment]
websocket连接成功

**Comment by wangzhengnan** [comment]
主版本websocket有问题，分支ok的

**Comment by im-qq** [comment]
试试develop分支的？在这个分支才比较完善websocket

**Comment by ealpha** [comment]
develop 正常的吗？

**Comment by im-qq** [comment]
develop正常的，目前我们内部线上正在使用的websocket。

**Comment by heipacker** [comment]
为啥还没合并到master呢？
