### ISSUE TITLE
comet跑了几个小时后cpu占用超高，但是没几个用户，有遇到相同问题的吗？

### ISSUE THREAD

**Issue by chenlongwill** [Terry-Mao/goim#143]

**Comment by im-qq** [comment]
那个分支呢，go版本、性能数据可以贴一下看看？

**Comment by chenlongwill** [comment]
@im-qq 
http://58.220.31.249:8010/20161101/5818724fe138235985000045.png

**Comment by af913337456** [comment]
找到问题所在了？

**Comment by im-qq** [comment]
@chenlongwill 目前版本并没有遇到该问题，我们线上也是一直在跑着。应该是修改代码导致的bug？

**Comment by chenlongwill** [comment]
修改代码导致的bug，因为想做一个用户进入多聊天室，之前就简单的把用户channel put进房间那个接口，出现的这个问题，现在代码变动比较大，bucket被我重写了，历史聊天记录用了redis存取，kafak聊天记录查询你们有做这方面的api么？用户也只允许单设备登陆，因为业务数据同步问题不方便。
