### ISSUE TITLE
关于Auth的流程？

### ISSUE THREAD

**Issue by tjx83** [Terry-Mao/goim#144]
通过tcp的方式连接服务器时，会有一个auth的过程，client->comet->logic，client在proto.body中存放数据，comet把这个数据作为token传入logic，logic将此token进行parseInt，然后作为userId进行进一步的操作。（不知道我描述得是否正确）
请教一下，为什么userId让客户端传入呢？

**Comment by im-qq** [comment]
这看要授权做法，比如你通过token可以查询到userID那也是可以的，也有的可能是通过userID和token一起传也没问题的

**Comment by tjx83** [comment]
多谢解释：）
