### ISSUE TITLE
job 报错

### ISSUE THREAD

**Issue by lijiansgit** [Terry-Mao/goim#149]
并发测试了一段时间后会出现下面这个报错：
[2016/12/12 15:17:59 CST] [EROR] [main.push:58] room.Push({\"test\": 2312312312312312312312312312312231312312312312312312312}
) roomId:&{%!d(string=room proto chan full)} error(%!v(MISSING))

求解，里面的chan full 具体是指的什么满了，这个错误改怎么解决

**Comment by liutaihua** [comment]
你可以调整一下job.conf内的配置，把room配置选项中的batch改大一点。  
这个错误是因为往一个预置了buffer的chan中塞入消息，然后buffer已经满了。    
原因可能是你配置batch比较小，同时推送压力比较大，导致chan的消费者处理不过来。

**Comment by im-qq** [comment]
这是一个房间每秒最大发送消息限制，可以在配置里面按需要进行调整的，消息太多对于用户也是看不完的，反而控制消息数量才达到更好的体验。

**Comment by lijiansgit** [comment]
调整过batch的配置之后问题已经解决，多谢两位
