### ISSUE TITLE
离线消息处理的问题

### ISSUE THREAD

**Issue by Willwww** [Terry-Mao/goim#151]
1.可以为某个用户订阅一个主题吗，这样会不会有性能问题呢、
2.如果不为每个用户订阅主题，用户不在线时的消息，该怎么处理比较好呢。

**Comment by liutaihua** [comment]
1, 你说的主题是指kafka topic么，基本上这样做不可行，随便来个几万人，topic会炸掉
2，离线消息应该自己用其他方式做，存redis之类的。上线的时候根据一定逻辑计算你的离线消息吧，具体看你的redis方案了。

**Comment by Willwww** [comment]
是指的kafka topic, 要是可行，离线的情况就比较好处理了.

**Comment by ilaotan** [comment]
kafka的topic超过64个,性能会急速下降,这个在云栖有人分享过测试数据
