### ISSUE TITLE
推送消息

### ISSUE THREAD

**Issue by lijiansgit** [Terry-Mao/goim#155]
在客户端连接有3W的时候推送数据就非常吃力了。推送的并发大概30条/s。怎么才能提高推送并发呢

**Comment by im-qq** [comment]
可以调整goruntine数量，以及bucket数量试试

**Comment by lijiansgit** [comment]
是要改动logic的代码吗

**Comment by im-qq** [comment]
不用的，推送时压力应该都在comet上面，可以调整goruntine看看

**Comment by lijiansgit** [comment]
push http接口并发很低。我用的是http接口推送的。就是这个：curl -d "{\"test\": 1}" http://127.0.0.1:7172/1/push/room?rid=1  应该是logic和router 之间有问题吧。logic和router负载都很低的

**Comment by lijiansgit** [comment]
多谢。搞定了。
