### ISSUE TITLE
goim是不是如下处理流程

### ISSUE THREAD

**Issue by 94else** [Terry-Mao/goim#157]
步骤
1.一个终端auth成功后获取到token
2.所有该终端的操作都是自己带有token发送到comet端，comet通过Operate接口转发到logic处理的

那么在该终端没有断开连接之前，另一个终端获取到了该终端的token就能冒充该终端进行任何操作了？

**Comment by im-qq** [comment]
用户可以通过https进行登录，得到token后，建立长连接；token是登录凭证，一般api中也是类似的，如果想达到绝对安全，可以考虑TLS方式
