### ISSUE TITLE
可以保持一条连接不断, 变换我们感兴趣的room吗？

### ISSUE THREAD

**Issue by heipacker** [Terry-Mao/goim#158]
rt

**Comment by im-qq** [comment]
应该问题不大，通过operation对应的client key，在对应bucket修改一下room可以了

**Comment by heipacker** [comment]
＠im-qq　需要改下代码是吧　加一个operation类型？

**Comment by im-qq** [comment]
修改一下可以到，在auth时也要把key返回给客户端。

**Comment by Terry-Mao** [comment]
这个可以自己实现，把对下的room改变，目前goim没做支持，可以自己实现@heipacker
