### ISSUE TITLE
推送消息

### ISSUE THREAD

**Issue by lijiansgit** [Terry-Mao/goim#159]
能实现控制推送消息的速度或者并发数量吗？比如消息每秒达到100条就丢弃。发现如果这个不做控制，带宽有可能会上限从而造成网络瘫痪。

**Comment by im-qq** [comment]
在job这边有配置，默认是40条/秒

**Comment by lijiansgit** [comment]
好的。但是系统广播类型性质的也会限制住了吧。能不能只针对用户发的消息类型做限制

**Comment by im-qq** [comment]
用户到用户的消息，一般都应该到达吧，并且用户消息也不可能太多的，一般有可能是在发送消息速度做限制

**Comment by lijiansgit** [comment]
不做限制的话，带宽会上限会，导致服务都无法正常通信了。用户发的是弹幕，丢了也没关系的，他自己是能看到自己的弹幕的

**Comment by im-qq** [comment]
限制可以考虑在logic中做的，在下行时过虑单个房间的速率，对于用户发弹幕可以限制几秒一条这样子，而是提醒用户发弹幕太快了
