### ISSUE TITLE
接口设计方面的小问题

### ISSUE THREAD

**Issue by heipacker** [Terry-Mao/goim#160]
func (a *DefaultAuther) Auth(token string) (userId int64, roomId int32)
改成这个
func (a *DefaultAuther) Auth(token string) (userId int64, roomId int32, err error)
是不是更好一点呢, 你们如果认证失败怎么返回？

**Comment by heipacker** [comment]
这里应该如果我认真失败了应该就返回一个error　然后在调用auth的地方封装这块, 这个就完美了，　但是现在这里　好像很别扭的

**Comment by im-qq** [comment]
这里只是一个示例，我们实际项目上也有return err，按实际修改auth.go

**Comment by heipacker** [comment]
好吧, 楼主不把你们实际项目的分享出来吗．．．

**Comment by im-qq** [comment]
每个系统的auth都是不一样的，看具体业务处理啊

**Comment by heipacker** [comment]
其实我说的不是auth的实现　是调用auth的那个地方的实现　这个地方应该是业务无关的
