### ISSUE TITLE
发送消息job就挂掉了

### ISSUE THREAD

**Issue by heipacker** [Terry-Mao/goim#161]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x80cfcec]

goroutine 55 [running]:
panic(0x84277e0, 0x18926008)
	/home/skywell/go/src/runtime/panic.go:500 +0x331
sync/atomic.AddUint64(0x1891a98c, 0x1, 0x0, 0x1, 0x1)
	/home/skywell/go/src/sync/atomic/asm_386.s:112 +0xc
main.(*Comet).Push(0x1891a960, 0x189b6150, 0x0, 0x0)
	/home/skywell/go_workspace/src/goim/logic/job/comet.go:50 +0x1cb
main.mPushComet(0x1, 0x189b1de0, 0x1, 0x4, 0x189cd5d0, 0xa, 0xc)
	/home/skywell/go_workspace/src/goim/logic/job/comet.go:162 +0x177
main.processPush(0x18a30a40)
	/home/skywell/go_workspace/src/goim/logic/job/push.go:36 +0x7b
created by main.InitPush
	/home/skywell/go_workspace/src/goim/logic/job/push.go:27 +0x107

**Comment by heipacker** [comment]
https://github.com/golang/go/issues/6404

**Comment by heipacker** [comment]
type Comet struct {
	serverId             int32
	rpcClient            *xrpc.Clients
	pushRoutines         []chan *proto.MPushMsgArg
	broadcastRoutines    []chan *proto.BoardcastArg
	roomRoutines         []chan *proto.BoardcastRoomArg
	pushRoutinesNum      int64
	roomRoutinesNum      int64
	broadcastRoutinesNum int64
	options              CometOptions
}
change to
type Comet struct {
	serverId             int32
	rpcClient            *xrpc.Clients
	pushRoutines         []chan *proto.MPushMsgArg
	broadcastRoutines    []chan *proto.BoardcastArg
	roomRoutines         []chan *proto.BoardcastRoomArg
        _                                 uint32
	pushRoutinesNum      int64
	roomRoutinesNum      int64
	broadcastRoutinesNum int64
	options              CometOptions
}

**Comment by im-qq** [comment]
32bit机器可以修改为int64应该就好了

**Comment by heipacker** [comment]
没试过，　这个解决方法是兼容的
