### ISSUE TITLE
关于xrpc线程池的疑惑

### ISSUE THREAD

**Issue by laohanlinux** [Terry-Mao/goim#167]
貌似goim里面的RPC只做容灾，而不做负载，这样设计的原因是什么呢？

**Comment by im-qq** [comment]
目前做法比较简单，还没加上服务发现，以及load balancing，因为我们线上看还是比较稳定的，依赖也少，而内部微服务关系复杂才做了完整的服务发现、连接池、负载均衡。

**Comment by laohanlinux** [comment]
恩，我们这边也修改了一下，给**xrpc**加上了容灾以及负载，但是`comet`通过`LVS`连接到`logic`不一定能够均匀，其长链可能只连到某台**logic**,感觉`LVS`这一层可以去掉
