### ISSUE TITLE
文档里好像没有介绍goim的压测情况

### ISSUE THREAD

**Issue by wangxingge** [Terry-Mao/goim#168]
To Terry, 

如果可以介绍一下goim的单台压测结果就更好了，我们目前也在选型推送框架，我不想自己再造轮子，想用你们的GOIM做个车就可以了，老司机，你停一下带带我呗。

**Comment by wangxingge** [comment]
好像更新了，Closed.

**Comment by im-qq** [comment]
目前我们线上单台10~100W左右都有跑到过，连接数量还是取决于内存大小较多，线上推消息量还是要看业务，我们一般感觉问题不大，比如私信重在连接数量，而直播重在消息量。
