### ISSUE TITLE
How the project runs in windows10 environment

### ISSUE THREAD

**Issue by xifumengmengda** [Terry-Mao/goim#169]
My computer is windows10，and The development environment is completed，but Step 1 （$ yum -y install java-1.7.0-openjdk）I do not go on。The yum command is a linux command。so  what should i do?

**Comment by im-qq** [comment]
You need to install the oracle Java to deploy kafka and zookeeper, and compile goim program to run it.

**Comment by zhouweitong3** [comment]
Well,goim currently does not support Windows platform.Only Linux is supported.
