### ISSUE TITLE
关于Websocket GC优化

### ISSUE THREAD

**Issue by yushengery** [Terry-Mao/goim#173]
你好，我们的项目中也用到了websocket，当并发量一大了之后，gc剧增，内存爆涨，我看到你这个协议支持WebSocket，但是官方的Websocket在http的协议之上进行hijack，从而会造成原来从pool分配出来的newBufioReader,newBufioWriteSize不会被放回到池子中，另外hijack它自己又会重新再new一个Writebuf，最终这些对象都需要gc去进行清理，有办法可以优化吗？
Best Regards

**Comment by linminglu** [comment]
新版本内存泄漏更严重了

**Comment by Terry-Mao** [comment]
websocket，我们好像魔改过
