### ISSUE TITLE
如何禁止别人在我的goim服务器上推信息

### ISSUE THREAD

**Issue by cosdy** [Terry-Mao/goim#174]
别人只要知道我的goim服务器的ip地址和某些用户ID，就可以给他们推信息了，如何做到只有自己能在自己的web服务器端推消息，而禁止别人推信息？

**Comment by chuangyou** [comment]
暴露出来的推送接口加个鉴权不就好了。

**Comment by Terry-Mao** [comment]
自己要做鉴权了
