### ISSUE TITLE
这个项目没人更新了么？

### ISSUE THREAD

**Issue by liyun2060** [Terry-Mao/goim#180]
我想用在生产环境下，不知道稳定性与可用性如何

**Comment by im-qq** [comment]
目前已经稳定阶段，对于私信推送和广播消息稳定性和可用性还是可以的，现在事情比较多，还没有太多精力放在新玩法上面试试。

**Comment by liyun2060** [comment]
恩，我想将它用在直播间的消息推送上  不知道是否可行

**Comment by Terry-Mao** [comment]
可以的，我们自己就是用的goim 作为直播消息，
