### ISSUE TITLE
发送的那个JSON数据 seq是什么意思？

### ISSUE THREAD

**Issue by liyun2060** [Terry-Mao/goim#183]
这个seq是什么？ 没太搞懂  什么的序列？  是指定不同的comet服务器的意思么

**Comment by heipacker** [comment]
就是连接序号吧， 可能某个用户 在移动端,pc端建立了两个连接， 都到一个coment了， 那加一个序号，区分一下

**Comment by Terry-Mao** [comment]
是的，类似连接复用，seq用于区分不同的操作，看看HTTP2 协议涉及，类似
