### ISSUE TITLE
希望可以搞个docker镜像, 方便一条命令部署

### ISSUE THREAD

**Issue by zhaishuaigan** [Terry-Mao/goim#188]
如果有docker镜像, 部署起来就方便多了, 环境搭建很头疼, 使用的人不需要会go, 就可以快速根据文档开发客户端了

**Comment by zhouweitong3** [comment]
Issue [#193](https://github.com/Terry-Mao/goim/issues/193) may help you.

**Comment by Terry-Mao** [comment]
赞
