### ISSUE TITLE
几点密码学建议

### ISSUE THREAD

**Issue by byronhe** [Terry-Mao/goim#2]
有几点问题：
1.  aes.go的aes使用了ecb模式，这个模式有严重安全问题。
请参考: [wikipedia](http://zh.wikipedia.org/wiki/%E5%9D%97%E5%AF%86%E7%A0%81%E7%9A%84%E5%B7%A5%E4%BD%9C%E6%A8%A1%E5%BC%8F)
[stackoverflow](http://security.stackexchange.com/a/2203)

2. rsa 选择了PKCS1v15 padding模式，这也是比较旧的一个模式了，安全性不如更新的pss和oaep

golang有很先进的密码学算法库，几点建议：
1.对称部分，建议直接使用最先进的aead算法，可选的有2种：[aes-gcm](https://leanpub.com/gocrypto/read#leanpub-auto-aes-gcm)，chacha20-poly1305 ，
2.非对称部分，建议先改成 [rsa-oaep](http://golang.org/pkg/crypto/rsa/#EncryptOAEP) 2048比特做认证+密钥交换，后续完全可以改成 ecdsa+ecdh

**Comment by Terry-Mao** [comment]
非常感谢你的建议，rsa这个我会尽快修改。
ECC相关的我会之后看看，另外AES使用ECB主要是方便客户端不用传递IV（当然安全性不如CBC）。这个我也在评估是否是使用blowfish

另外，加密和解密这块通用性比较难，需求各不同，我会抽象出一个cryptor的接口，让调用者自己实现，默认会使用 rsa-oaep  + aes ecb

**Comment by byronhe** [comment]
IV这个，IV是不应该明文传递的，
建议用hkdf函数，把协商出来的 共享密钥延长成 一个长密钥字节流，然后从密钥流里面切割出各类iv,aes key，nonce implicit key 等等参数。

为什么要考虑blowfish？blowfish是个很陈旧的cipher了，无论是从安全性，还是性能(aes有硬件指令aesni)，都无法跟aes相比，建议不要用。<http://stackoverflow.com/questions/4147451/aes-vs-blowfish-for-file-encryption>

**Comment by byronhe** [comment]
对称加密这一块，其实可以直接用 go的nacl库里面的 [secret_box](https://godoc.org/golang.org/x/crypto/nacl/secretbox)

**Comment by Terry-Mao** [comment]
难道是我阅读的文章有误，居然说更好。。。http://blog.csdn.net/nightelve/article/details/16865773
另外，IV不会明文传递，应该会放到握手协议里面一起。
nonce implicit key 这个参数的作用是噪音么？

**Comment by byronhe** [comment]
性能可以自行测试，测试命令：

···
 openssl speed  bf
 openssl speed  aes-128-cbc
 openssl speed  -evp aes-128-cbc
···
分别是: bf，aes-128-cbc（软件实现版本），aes-128-cbc（使用aesni指令版本）



nonce implicit key指的是gcm模式的nonce的一个组成部分，<https://tools.ietf.org/html/rfc5288#section-3>。

嗯，后续我贡献点加解密这块的pr吧。

**Comment by Terry-Mao** [comment]
欢迎PR，我来把接口抽象出来，做成可配置的 握手协议加密实现。

**Comment by Terry-Mao** [comment]
可以加我Q：83873308，欢迎私聊面基。。。

**Comment by Terry-Mao** [comment]
已经抽象出 cryptor接口，使用了OAEP交换密钥和由原来的ECB修改成了CBC

**Comment by Terry-Mao** [comment]
密码模块已经从comet移除
