### ISSUE TITLE
为什么要java,能不能分服务器部署？

### ISSUE THREAD

**Issue by boneq** [Terry-Mao/goim#200]
yum -y install java-1.7.0-openjdk
为什么要用这个呢，
还有就是可以分服务器部署么？

**Comment by PuShaoWei** [comment]
同问

**Comment by zhouweitong3** [comment]
goim中用到基于Java的kafka作为消息队列服务器。运行kafka需要安装JDK。
目前最新版的kafka需要java-1.8.0-openjdk。
至于分服务器部署，官方说可以，我本人并没有试过。

**Comment by justein** [comment]
这个有在生产环境用的么，如何？

**Comment by zhouweitong3** [comment]
上海幻电公司（哔哩哔哩）的弹幕推送系统一部分使用了goim，具体可以参照中国国家专利 ` 201610511191.7 ` ，《一种弹幕推送系统及推送方法》

**Comment by smokemvp** [comment]
居然要依赖java.  就算再强,却也丢失了味道.

**Comment by Terry-Mao** [comment]
因为使用了Kafka作为Queue

**Comment by shunhua** [comment]
nats 呢
