### ISSUE TITLE
goim部署的错误

### ISSUE THREAD

**Issue by lifeinearth** [Terry-Mao/goim#206]
请问下，下面的问题是什么原因

# goim/libs/hash/murmurhash3
runtime.main: call to external function main.main
runtime.main: main.main: not defined
runtime.main: undefined: main.main
# github.com/Shopify/sarama
../github.com/Shopify/sarama/delete_records_request.go:96: undefined: sort.Slice
../github.com/Shopify/sarama/delete_records_response.go:99: undefined: sort.Slice
go build goim/router/test: no buildable Go source files in /data/apps/go/src/goim/router/test

**Comment by Terry-Mao** [comment]
go 版本问题
