### ISSUE TITLE
感觉是消息推送而不是IM

### ISSUE THREAD

**Issue by hanzhihua** [Terry-Mao/goim#209]
请问一下，客户端如何给一个用户发消息呢？好像这逻辑没有开源吧，多谢

**Comment by hanzhihua** [comment]
哦，logic模块是对外的吗？我以为是对内的模块，如果对外，如何确定发消息的人的身份？谢谢

**Comment by weisd** [comment]
client连接comet的时候有个auth(根据自己业务修改)获取uid,roomid, 把uid,roomid信息存到router
其他模块要发往哪个uid,roomid就从router里取

如何确定发消息的人的身份，这个属于你的业务逻辑

logic 可以对外也可以在外面再封装实现自己的业务逻辑

**Comment by hanzhihua** [comment]
那是不是comet只是一个推送通道，客户端主动发消息是走logic模块。这样设计，有点奇怪，本身客户端和comet维护了一个长链，而客户端发送消息不走这个通道，有点不能理解这样的设计：）

**Comment by hanzhihua** [comment]
作者能回一下吗？谢谢

**Comment by hanzhihua** [comment]
![image](https://user-images.githubusercontent.com/1732108/39753712-589ce9ba-52f2-11e8-8d89-1038a854e8a6.png)
这个代码没有实现吗？

**Comment by weisd** [comment]
如果你想用comet接收消息，可以自己实现
但是我觉得还是在logic接收比较好，方便加业务逻辑

**Comment by Terry-Mao** [comment]
目前交给自己实现的，im涉及各种存储有关的细节了
