### ISSUE TITLE
请问避免客户端重复登录

### ISSUE THREAD

**Issue by BigWhiteEat** [Terry-Mao/goim#210]
客户端每一次登录，那个key等于userid_seq，seq是自增的。但是有时候客户端会重复登录，导致同一个userid下有很多seq，其中很多是无效的。请问这个应该怎么处理？

看截图，会有很多个同一user的key。这个怎么把无效的去除？
![image](https://user-images.githubusercontent.com/14919425/39763953-07889078-5311-11e8-9367-bbe02de259ae.png)
![image](https://user-images.githubusercontent.com/14919425/39763958-0cac1304-5311-11e8-88d1-d0994d895558.png)

**Comment by weisd** [comment]
comet连接断开时会从router中del掉对应的连接的
但是如果comet重启，router确实会存在没删除掉的信息

**Comment by BigWhiteEat** [comment]
请问comet断开，需要客户端调用websocket的close方法吗？
这的comet心跳的方法。服务器怎么判断某个客户端的心跳超时的啊？超时的时候是怎么删除对应的连接的？
<img width="477" alt="2018-05-09 2 06 10" src="https://user-images.githubusercontent.com/14919425/39798262-58d8ed52-5392-11e8-9dd0-2d8e1cb8ac5e.png">

**Comment by weisd** [comment]
tr.Set(trd,hb) 是个timeAfter 如果超时服务器端会close掉连接，客户端发心跳会重置timeAfter时间

服务端close掉连接后，websocket会收到onClose事件，不用主动close

**Comment by BigWhiteEat** [comment]
非常感谢。
