### ISSUE TITLE
安装 commet报以下错误

### ISSUE THREAD

**Issue by gangdan0083** [Terry-Mao/goim#212]
# goim/comet
./socketio.go:21:33: syntax error: unexpected ), expecting }
./socketio.go:22:2: syntax error: non-declaration statement outside function body

**Comment by yeyute** [comment]
我也遇到了，改好了语法错误还是装不上

`./main.go:83:29: cannot use Conf.SocketioBind (type []string) as type string in argument to InitSocketIO
./socketio.go:57:26: cannot use ws (type *socketio.Socket) as type *websocket.Conn in argument to p.ReadWebsocket`

**Comment by Terry-Mao** [comment]
已经修复，移除了socketio
