### ISSUE TITLE
请教关于benchmark测试的问题

### ISSUE THREAD

**Issue by chenwin** [Terry-Mao/goim#219]
在https://github.com/Terry-Mao/goim/blob/master/doc/benchmark_cn.md里提到
========================
压测参数
不同UID同房间在线人数: 1,000,000
持续推送时长: 15分钟
持续推送数量: 40条/秒
========================
请问，在线人数1,000,000在哪里配置呢？

=========================
压测结果
推送到达: 3590万/秒左右;
=========================
请问，3590万怎么得出来的？

**Comment by tonyboxes** [comment]
在benchmark client启动不同uid的连接，然后推送时会记录收到countDown消息，然后进行合计的结果
