### ISSUE TITLE
logic 对应的 router client 的设计考虑

### ISSUE THREAD

**Issue by beiciye** [Terry-Mao/goim#221]
目前， logic 这里注册 router rpc 的时候会维护一个哈希环， 配置文件里面每个 serverID 对应着一个 router 节点数组。   最后也就是每个 userID 对应着一个 router 数组。  那么问题来了，每个 UserID 的信息是存在第一个可用的 router 节点上的， 倘若这个节点挂了。 logic 会默认选择下一个可用的 router 绩点， 调用 router 时并不会反应出节点挂了，而是找不到这个 userID 的信息。

请问一个 UserID 对应多个 router 节点，当时的考量是什么？

**Comment by tonyboxes** [comment]
目前v2.0通过redis记录在线信息，可以通过proxy配置hash方式，或者踢掉非正常的节点
