### ISSUE TITLE
golang版本支持到哪些版本？

### ISSUE THREAD

**Issue by linphy** [Terry-Mao/goim#222]
目前golang1.9  1.10编译都不通过

**Comment by linphy** [comment]
均报以下错误
go get ./...
# goim/libs/hash/murmurhash3
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"

**Comment by stackeric** [comment]
相同的问题，请问支持最高的版本是？

**Comment by bjbjbjbj** [comment]
> 均报以下错误
> go get ./...
> 
> # goim/libs/hash/murmurhash3
> runtime.main_main·f: relocation target main.main not defined
> runtime.main_main·f: undefined: "main.main"

一样，有解决方法么
