### ISSUE TITLE
过载保护怎么做的呢

### ISSUE THREAD

**Issue by lik0914** [Terry-Mao/goim#224]
比如经常遇到的场景， 一个大型直播间，突然来了好多人，涌入到房间，这个时候，连接建立比较慢，而且经常报错， 服务压力也很大，这个是怎么解决的呢

**Comment by beiciye** [comment]
加 comet 节点？

**Comment by beiciye** [comment]
comet 增加节点？

**Comment by Terry-Mao** [comment]
其实正确做法是 支持调度，需要客户端配合，类似304 CDN 调度，基于 在线数、带宽，负载等情况进行调度，以及限流
