### ISSUE TITLE
消息到达率怎么保证的呢

### ISSUE THREAD

**Issue by lik0914** [Terry-Mao/goim#225]
一个场景，比如一个用户在一个房间，给主播发了一个收费礼物， 直播间其他用户会收到礼物特效，这中场景，我感觉消息可到达比较重要，这块怎么保证的呢？

还有router问题，看之前帖子要解决这层的问题，现在解决了吗

**Comment by iamxvbaba** [comment]
保证可达，我想应该就实现一个队列。
每条消息都放进队列当中，当收到消息的时候返回指定的指令，从而这个队列当中移除。你这个场景要保证所有在线的人都收到 实现起来就麻烦些。

**Comment by lik0914** [comment]
@iamxvbaba 目前这个系统我看代码，貌似不支持离线消息吧

**Comment by iamxvbaba** [comment]
是的，目前离线的没有实现，自己加吧。
