### ISSUE TITLE
推送 后 job 报错

### ISSUE THREAD

**Issue by ppshjj521** [Terry-Mao/goim#228]
推送后job.log 报错如下：
kafka: error while consuming KafkaPushsTopic/0: kafka: error decoding packet: CRC didn't match expected 0x0 got 0xe38a6876

请问是什么原因 我用得go1.92 是因为版本的原因吗

**Comment by tonyboxes** [comment]
应该是kafka和client依赖库问题，建议升级最新的kafka client库。
