### ISSUE TITLE
看了源码round timer 这块代码没看明白呢

### ISSUE THREAD

**Issue by lik0914** [Terry-Mao/goim#231]
如题，谁能给指教一下呢

**Comment by liyonglion** [comment]
@lik0914 
round timer代码如下：
func (r *Round) Timer(rn int) *time.Timer {
	return &(r.timers[rn%r.options.Timer])
}
rn在调用的地方递增，添加time的所有操作都会均匀的分散到各个time.Timer对象上，这样不会对单个对象操作太大的压力，time.Timer使用切片实现了一个类似最小堆的算法，在堆得开头是最先超时的time点，没调用一次TImer.Add操作，都有可能调整一次堆。

**Comment by liyonglion** [comment]
@Terry-Mao  有一个疑问，在go time.TImer源码里面已经实现了最小堆算法，只需要复用Timer即可。为什么该代码里面还需要实现一次类似最小堆算法呢？golang timer[资料](https://tonybai.com/2016/12/21/how-to-use-timer-reset-in-golang-correctly/)

**Comment by Terry-Mao** [comment]
因为有全局大锁争用，在密集连接发送时候，容易出现futex 争用，所以通过自己实现timer，然后减少对系统层面的timer调用

**Comment by xiaoxiaoyu85** [comment]
@Terry-Mao 首先感谢开源大作，已经拜读了，收益不少。有几个问题:   从tcpWriteProto开始的数据发送，没有设置发送超时，这样发送goroutine会被挂起，直到底层epoll接收到新的"通知事件",这里方便优化下加个超时吗？ 读取应该也是一样的

**Comment by xiaoxiaoyu85** [comment]
@Terry-Mao 首先感谢开源大作，已经拜读了，收益不少。有几个问题: 从tcpWriteProto开始的数据发送，没有设置发送超时，这样comet发送goroutine会被挂起，直到底层epoll接收到新的"通知事件",这里方便优化下加个超时吗？

**Comment by weisd** [comment]
超时后什么处理？消息丢弃？
