### ISSUE TITLE
不管是自行部署还是使用zhouweitong的docker镜像都出现comet和kafka broker冲突的问题

### ISSUE THREAD

**Issue by xdjakiechen** [Terry-Mao/goim#232]
现象是镜像启动后comet没有起来，手动./comet -c comet.conf之后，kafka服务自动停止了。
之后执行  ./bin/kafka-server-start.sh config/server.properties，发现comet自动退出了，请问下有人遇到这个问题吗？

**Comment by bjbjbjbj** [comment]
> 现象是镜像启动后comet没有起来，手动./comet -c comet.conf之后，kafka服务自动停止了。
> 之后执行 ./bin/kafka-server-start.sh config/server.properties，发现comet自动退出了，请问下有人遇到这个问题吗？

能把log发一下来看看么

**Comment by xdjakiechen** [comment]
估计可能还是版本的问题的问题导致，跑镜像是没问题了
