### ISSUE TITLE
white.list处理的一点疑问

### ISSUE THREAD

**Issue by y6828863** [Terry-Mao/goim#237]
按照whitelist.go中的逻辑以及样例comet配置文件中的white.list 123_,321_ 的配置不难看出白名单是需要后缀是"_"结尾的，但是我在配置文件解析的逻辑里面并未看到在解析配置文件的时候对这个下划线"_"进行任何去除处理，并且在代码的其它地方也没有找到，那么这样的话在这个Contains（key string）方法被调用的时候无论是写123还是123_，始终结果返回都会是false，那么这段白名单的设置逻辑不就是有问题吗？请帮忙解答一下，多谢！

`// Contains whitelist contains a key or not.
func (w *Whitelist) Contains(key string) (ok bool) {
	if ix := strings.Index(key, "_"); ix > -1 {
		_, ok = w.list[key[:ix]]
	}
	return
}`

**Comment by tonyboxes** [comment]
ix := strings.Index(key, "_")
ix已经包括了_下标，所以配置里面  {userid}_ 是可以正常匹配到了，前提是key带有userid的情况下

**Comment by y6828863** [comment]
> ix := strings.Index(key, "_") ix已经包括了_下标，所以配置里面 {userid}_ 是可以正常匹配到了，前提是key带有userid的情况下

如果key="1234_"那么 key[:strings.Index(key, "_")] ===>key[:4]也就是1234，这种处理把下划线给去掉了，所以在配置文件解析的时候如果没有任何处理操作的话，Whitelist里面的"1234_"中的下划线没有去掉，这样无论如何也匹配不到“1234”。

**Comment by y6828863** [comment]
> white.list 111,222,333
> 
> 我看了一下线上配置，实际上只是配置了userID而已，应该没带 "_"，估计是example写错了奥

OK，那说明我的理解和源码阅读的没有啥问题，多谢！
