### ISSUE TITLE
channal.push的时候signal chan在阻塞的情况下走default那不是会丢消息？

### ISSUE THREAD

**Issue by weisd** [Terry-Mao/goim#240]
https://github.com/Terry-Mao/goim/blob/35e3a4830973a59638fd44314bda70989362d9ae/internal/comet/channel.go#L87

```
// Push server push message.
func (c *Channel) Push(p *grpc.Proto) (err error) {
	select {
	case c.signal <- p:
	default:
	}
	return
}
```
如题

**Comment by tonyboxes** [comment]
要是需要确保消息也可以阻塞下，不过对于消费量大或者服务端流量打满丢包时有点风险，也可以配置buff proto大小尽量避免
