### ISSUE TITLE
菜鸟请教下，这个直接部署就能用？还是要自己改改源码？

### ISSUE THREAD

**Issue by zhuwei** [Terry-Mao/goim#242]
不好意思，实在没搞懂，怎么创建一个用户？文档里好像只有  push消息协议

**Comment by tonyboxes** [comment]
需要实现logic里面的auth才可以，v2文档正在逐步补全到wiki中

**Comment by zhuwei** [comment]
@tonyboxes 非常感谢，期待您的文档

**Comment by dempsey-ycr** [comment]
请问你有遇到这个问题吗？ discovery一直报404:
discovery: client.Get(http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&appid=goim.logic&env=&hostname=bogon&latest_timestamp=0&latest_timestamp=0) get error code(-404)
