### ISSUE TITLE
mid是什么意思

### ISSUE THREAD

**Issue by tangzhenquan** [Terry-Mao/goim#243]
我在goim 2.0版本里面看到有mid不太理解，请问一下是用来干什么的？跟业务相关？

**Comment by tonyboxes** [comment]
memberid，v1应该是userid，意思应该同样的，支持key、user、room和broadcast几种推送方式

**Comment by tangzhenquan** [comment]
@tonyboxes  谢了

**Comment by dempsey-ycr** [comment]
说实话 文档还缺很多

**Comment by wuwentao1998** [comment]
push API文档里可以注明下吗？
