### ISSUE TITLE
MAC安装部署

### ISSUE THREAD

**Issue by xiaoguiSniper** [Terry-Mao/goim#246]
说明是基于LINUX的,有没有基于MAC OS 的指导呢

**Comment by xiaoguiSniper** [comment]
非常感谢你的技术支持.

**Comment by xiaoguiSniper** [comment]
还有想问,有关于2.0的部署接入文档在哪里能找到呢,对于小白想要接入上手并着手logic的实现好像有点困难.

**Comment by tonyboxes** [comment]
可以在goim.io看看相关文档

**Comment by dempsey-ycr** [comment]
请问你有遇到这个问题吗，discovery一直报404:
discovery: client.Get(http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&appid=goim.logic&env=&hostname=bogon&latest_timestamp=0&latest_timestamp=0) get error code(-404)

**Comment by tonyboxes** [comment]
@dempsey-ycr makefile flag错误了，已经修复了

**Comment by xiaoguiSniper** [comment]
> @dempsey-ycr makefile flag错误了，已经修复了

我也遇到了相同的问题,所有代码都是今天最新拉取的.
`E0121 15:27:57.879723   11426 client.go:582] discovery: client.Get(http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&env=dev&hostname=SniperdeMacBook-Pro.local&latest_timestamp=1548055310053396000) error(Get http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&env=dev&hostname=SniperdeMacBook-Pro.local&latest_timestamp=1548055310053396000: context canceled)
E0121 15:27:57.886782   11426 client.go:587] discovery: client.Get(http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&appid=goim.logic&env=dev&hostname=SniperdeMacBook-Pro.local&latest_timestamp=1548055310053396000&latest_timestamp=0) get error code(-404)`

**Comment by xiaoguiSniper** [comment]
额 没活跃的人在吗
