### ISSUE TITLE
为发送消息有3秒左右的延迟

### ISSUE THREAD

**Issue by hcj112** [Terry-Mao/goim#252]

**Comment by hcj112** [comment]
2.0的发消息有延迟3秒左右,作者有没有遇到,能解答一下么?

**Comment by tonyboxes** [comment]
是在什么环境下进行推送的呢？比如什么量级和对应配置

**Comment by hcj112** [comment]
cpu 32核,内在32G,带宽5Mbps
job,comet,logic,dicovery 和 live都在这台测试机器上,一个房间人数就几个人

**Comment by hcj112** [comment]
都是走的websocket

**Comment by tonyboxes** [comment]
默认job会有1s的批量消息聚合，加上链路延迟应该差不多

**Comment by igo9go** [comment]
不能实时推送吗

**Comment by tonyboxes** [comment]
@igo9go 什么场景的呢，1s聚合可以带来很大的性能优化，已经相当实时了

**Comment by wangbon** [comment]
> live
请问下要如何才能看到时延 ？（需要部署一个真的live视频播放吗？然后通过websocket来访问观看？）如能解答十分感谢，不能，那就打扰咯。
