### ISSUE TITLE
按readme部署，出现以下问题。请教大佬...

### ISSUE THREAD

**Issue by dempsey-ycr** [Terry-Mao/goim#253]
comet logic job 模块在控制台一直打印：
E0114 16:40:39.292580   95634 client.go:589] discovery: client.Get(http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&env=&hostname=bogon&latest_timestamp=0) get error code(-404)
E0114 16:40:40.298348   95634 client.go:589] discovery: client.Get(http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&appid=goim.comet&env=&hostname=bogon&latest_timestamp=0&latest_timestamp=0) get error code(-404)

discovery打印：
Polls zone() env() appid(infra.discovery) error(-404)
http.go:73] METHOD:GET | PATH:/discovery/polls?appid=infra.discovery&env=&hostname=bogon&latest_timestamp=0 | CODE:200 | IP:127.0.0.1 | TIME:0 | ECODE:-404

**Comment by tonyboxes** [comment]
env看着为空，看看是否有指定-deploy.env=dev

**Comment by dempsey-ycr** [comment]
都有指定。是按着最新文档来的。发现comet中context canceled：
discovery: client.Get(http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&appid=goim.logic&env=&hostname=bogon&latest_timestamp=0&latest_timestamp=0) error(Get http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&appid=goim.logic&env=&hostname=bogon&latest_timestamp=0&latest_timestamp=0: context canceled)

**Comment by zjzhang-cn** [comment]
是Makefile的问题deploy.env=dev前面没有-号

**Comment by dempsey-ycr** [comment]
@zjzhang-cn 果然是， 多谢大佬指点🙈。。

**Comment by tonyboxes** [comment]
@zjzhang-cn 感谢反馈，已经修复了
