### ISSUE TITLE
websocekt 连接comet错误

### ISSUE THREAD

**Issue by dempsey-ycr** [Terry-Mao/goim#255]
"ws://127.0.0.1:3102/sub" 使用该url发送消息，comet日志错误如下：
E0115 20:40:51.857977   17225 server_websocket.go:226] key:  remoteIP: 127.0.0.1:49911 step: 4 ws handshake failed error(default server codec pack length error)

**Comment by dempsey-ycr** [comment]
希望作者大佬有空能修改和丰富一下文档。。。

**Comment by tonyboxes** [comment]
直接连接demo server试试可以正常不，有可能是客户端发包不对？http://goim.io/examples/

**Comment by tonyboxes** [comment]
benchmark应该是tcp端口3101，不能连websocket端口

**Comment by dempsey-ycr** [comment]
@tonyboxes 是的 我知道。我也是这么做的。但是一直就报那个错误，无论我用你的push代码还是自己写的ws client 都是如此

**Comment by tonyboxes** [comment]
3101是tcp长连接端口，并不是http的

**Comment by tonyboxes** [comment]
可以看看arch图理解下模块

**Comment by dempsey-ycr** [comment]
哦，对的。 benchmarks都是http的，那其下的push都是连接测试logic模块用的？而连接comet模块的demo是examples下的client.js?

**Comment by tonyboxes** [comment]
可以看具体业务实现，通过http会方便很多

**Comment by dempsey-ycr** [comment]
感谢帅佬的耐心讲解。我的问题问完了
