### ISSUE TITLE
bucket 结构疑问

### ISSUE THREAD

**Issue by jsaaae** [Terry-Mao/goim#256]
为什么是每个bucket保存部分channel ，而不是全局一个保存所有channel？bucket只保存room  ，用roomid 映射到一个bucket上， 现在的bucket设计会有同一个room 在不同bucket上吧，这样做有什么好处吗？

**Comment by tonyboxes** [comment]
这个类似nginx worker，可以分散锁的竞争

**Comment by huangyunbo** [comment]
@jsaaae @tonyboxes 我有相同的疑问相同的room，应该会在不同的bucket出现多次。

**Comment by huangyunbo** [comment]
@jsaaae @tonyboxes 我有相同的疑问
1、创建ch的时候，会根据key计算cityhash，查找应该放到具体的bucket。
2、然后在对应的bucket会查找roomid是否存在，没有就创建。
