### ISSUE TITLE
大过年的，再问作者一个问题，先说一声过年好

### ISSUE THREAD

**Issue by BigWhiteEat** [Terry-Mao/goim#260]
我用supervisor开启goim的四个模块，然后在运行时候job模块出现问题了。
此时logic、comet、router都是正在运行重的，但是job和kafka部分一直报错
这个是job下面的日志，请问这个是怎么回事啊？
<img width="970" alt="2019-02-03 9 41 28" src="https://user-images.githubusercontent.com/14919425/52177571-e1cc9100-27fd-11e9-8087-a771ec0421e7.png">

**Comment by tonyboxes** [comment]
这个看着comet应该没连接上rpc也一直保存，看看comet有起来不呢

**Comment by BigWhiteEat** [comment]
comet挂了supervosor会自动重启的啊。
而且，这个job挂掉后，就没法启动了,错误是：
panic: kafka: invalid configuration (You must provide at least one broker address)
重启kafka、zookeeper也没用
得把job二进制文件删掉，重新打包上传才可以启动。
这个怎么回事啊

**Comment by tonyboxes** [comment]
export http_proxy 加个代理或者本地编译再传过去也可以
