### ISSUE TITLE
作者过年好，小白遇到一个问题cmd/comet/main.go:19:2: use of internal package not allowed

### ISSUE THREAD

**Issue by wangbon** [Terry-Mao/goim#261]
在执行go get ./...时 只要是internal里的包引用都会出现上述的问题 这是为什么呀，十分抱歉问这样的问题，查了说是内部包不能被外部访问，可是为什么pkg里的ip包就没这个显示呢？

**Comment by tonyboxes** [comment]
go version看看那个版本的呢，clone下来直接go build会下载依赖的

**Comment by wangbon** [comment]
go version是 go1.9.2.linux-amd64, 我的操作就是 go get -u github.com/Terry-Mao/goim , 会提示我没有可执行的go 文件，在goim目录下go get ./... 然后就提示上述问题啦  谢谢解答，我再看看哈

**Comment by tonyboxes** [comment]
go mod需要go 1.11才支持，建议升级一下

**Comment by wangbon** [comment]
换了，执行了 go build。会发现golang.org/x/net 与google.golang.org/grpc 因为连接不上，不能下载这部分的代码，我的环境是在云上，不能建VPN。尴尬了，怎么解决呢（上述两个的github代码地址我可以找到）。现在就是执行go build, 它先检查可达性，有连接不上的，其他都执行不下去么？

**Comment by wangbon** [comment]
查到一个replace的方法，试一试0.0

**Comment by tonyboxes** [comment]
export http_proxy 加个代理或者本地编译再传过去也可以

**Comment by wangbon** [comment]
谢谢作者（我试了下你的方法 加代理，成功了，就是我找的代理不稳定）最后我买了一台位于香港的云服务器来解决
