### ISSUE TITLE
启动发生错误

### ISSUE THREAD

**Issue by xiaoguiSniper** [Terry-Mao/goim#264]
作者你好，我在执行了 make run后，在comet中,遇到以下错误：
`true`

`E0211 10:19:23.961804    3882 client.go:582] discovery: client.Get(http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&env=dev&hostname=SniperdeMacBook-Pro.local&latest_timestamp=1549851375317716000) error(Get http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&env=dev&hostname=SniperdeMacBook-Pro.local&latest_timestamp=1549851375317716000: context canceled)`

`E0211 10:19:23.964157    3882 client.go:587] discovery: client.Get(http://127.0.0.1:7171/discovery/polls?appid=infra.discovery&appid=goim.logic&env=dev&hostname=SniperdeMacBook-Pro.local&latest_timestamp=1549851375317716000&latest_timestamp=0) get error code(-404)`

**Comment by wangbon** [comment]
hello 请问这个问题 你解决了吗  ？  我也遇到了类似的

**Comment by tonyboxes** [comment]
这个需要单独启动下discocery作为服务发现

**Comment by xiaoguiSniper** [comment]
@tonyboxes 我这边`./discovery -conf discovery-example.toml -alsologtostderr`使用这个启动了discovery服务的

**Comment by xiaoguiSniper** [comment]
> hello 请问这个问题 你解决了吗 ？ 我也遇到了类似的

暂时还没有。你呢
