### ISSUE TITLE
服务器流量跑得快

### ISSUE THREAD

**Issue by BigWhiteEat** [Terry-Mao/goim#266]
作者你好，请问goim的几个模块和kafka、zookeeper消耗的流量大吗？
我在腾讯云部署了goim，目前只有几个用户在测试，但是每个月腾讯云的流量要超好几百，请问是不是goim本身流量消耗大还是服务器的问题？

**Comment by iamxvbaba** [comment]
腾讯云..............  先检查自己的服务器有啥问题吧

**Comment by tonyboxes** [comment]
这个估计你需要确定是内网流星，还是外网流量；
比如：
1、comet模块是对公网流量，跟用户建立长连接；
2、logic/job/kafka这些是内网流量，主要看推送和消息大小；
