### ISSUE TITLE
websocket 相关逻辑的问题

### ISSUE THREAD

**Issue by pslzym** [Terry-Mao/goim#268]
非常感谢作者们开源这么好的代码。
我在看源码的时候看到websocket 的逻辑基本全都是作者自己做的相关的处理，有点好奇为什么不使用gorilla/websocket？
作者2.1的roadmap也有websocket 的相关功能（permessage-deflate压缩），其中gorilla/websocket库里面基本已经实现了。
是不是有其他方面的考虑？

**Comment by tonyboxes** [comment]
现在pkg中使用了跟tcp模块的buff复用，对gc有一定的优化，压缩有尝试写过，不过对内存复用还没很好解决。
gorilla/websocket，可能对内存分配，以及frame header都是实时分配，比较担心比较大的在线room对性能有一定的影响。

**Comment by pslzym** [comment]
谢谢作者的解答。
还有一个问题想要请教一下作者，如果想用goim配合存储和推送离线的消息，使之成为一套IM。有没有其他的方案可以一起配合使用的？

**Comment by tonyboxes** [comment]
存储部分需要自己根据业务实现，看数据量可以结合redis和mysql，或者一些kv存储
