### ISSUE TITLE
关于个性化开发

### ISSUE THREAD

**Issue by xiaoguiSniper** [Terry-Mao/goim#272]
作者你好，在跑goim项目时，我需要加入鉴权等接口，这种接口应该写在什么位置呢

**Comment by tonyboxes** [comment]
可以写在logic connect里面

**Comment by xiaoguiSniper** [comment]
accepts的参数的含义是什么呢

**Comment by tonyboxes** [comment]
客户端需要推送的operations，看看业务是否需要

**Comment by xiaoguiSniper** [comment]
op是自己定义还是项目已经定义好了？




——————————————————
   Best Regards!
============================
张跃辉 - Technical Consultant
E-mail: yuehui.zhang@hand-china.com
Mobile:13540863133
HAND Enterprise Solutions Co.,Ltd.
上 海 汉 得 信 息 技 术 股 份 有 限 公 司
============================
在2019年02月25日 19:48，Tony 写道：

客户端需要推送的operations，看看业务是否需要

**Comment by tonyboxes** [comment]
客户端支持哪些op应该是已经定义好的

**Comment by xiaoguiSniper** [comment]
定义好的op 有没有接入文档呢，在哪查看每个op对应的含义

**Comment by tonyboxes** [comment]
这个是业务已经定义的op

**Comment by xiaoguiSniper** [comment]
抱歉没找到对每个op指定的操作是什么

**Comment by oasangqi** [comment]
> 抱歉没找到对每个op指定的操作是什么

你业务层自己定义op吧，goim只是提供这么个功能

**Comment by tsingson** [comment]
> 抱歉没找到对每个op指定的操作是什么

op 代码定义在 /api/comet/grpc/operation.go 文件中有定义, 并且在 logic 的 grpc server 端有处理函数, 你扩展这些函数就可以了.

**Comment by tonyboxes** [comment]
@tsingson nice!
