### ISSUE TITLE
go buildable error

### ISSUE THREAD

**Issue by kamajoy** [Terry-Mao/goim#274]
在拉取代码的时候执行：
go get -u github.com/Terry-Mao/goim
后出现下面的错误，是什么原因导致的呢
package github.com/Terry-Mao/goim: no buildable Go source files in /data/apps/go/src/github.com/Terry-Mao/goim

最后发现项目代码里面也没有 goim/router目录 ，即没有 cd $GOPATH/src/goim/router

请问这是什么原因导致的呢。

**Comment by wangbon** [comment]
需要使用go1.11以上版本。  现在2.0代码已经没有router了，改用redis了 ,可以在goim.io先看看

**Comment by kamajoy** [comment]
> 需要使用go1.11以上版本。 现在2.0代码已经没有router了，改用redis了 ,可以在goim.io先看看

好的，谢谢。
