### ISSUE TITLE
请教一下编译时提示grpc及x/net安装不上怎么解决

### ISSUE THREAD

**Issue by liming127** [Terry-Mao/goim#286]
翻墙后google能正常打开，编译时grpc与x/net依然提示超时，使用网上替代方案安装后再编译，依然提示未安装这两个库

**Comment by fananchong** [comment]
go build 前添加 export GOPROXY=https://goproxy.io ， 使用这个代理即可

**Comment by liming127** [comment]
> go build 前添加 export GOPROXY=https://goproxy.io ， 使用这个代理即可

export GOPROXY=https://goproxy.io
rm -rf target/
mkdir target/
cp cmd/comet/comet-example.toml target/comet.toml
cp cmd/logic/logic-example.toml target/logic.toml
cp cmd/job/job-example.toml target/job.toml
GO111MODULE=on go build -o target/comet cmd/comet/main.go
go: google.golang.org/grpc@v1.16.0: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20181011144130-49bb7cea24b1: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: error loading module requirements
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 1


是这样加的吗，我是在makefile文件，build后第一行加入

**Comment by liming127** [comment]
我安装的是go 1.12版本，会有影响吗

**Comment by xiaoguiSniper** [comment]
不是让你加在makefile里面 你执行命令之前 先加代理，为了确保代理没问题 你加完代理过后 可以命令行请求一下谷歌 看能否有数据返回 确保没问题过后 你在执行go build

**Comment by liming127** [comment]
> 不是让你加在makefile里面 你执行命令之前 先加代理，为了确保代理没问题 你加完代理过后 可以命令行请求一下谷歌 看能否有数据返回 确保没问题过后 你在执行go build.还有你的翻墙只是让你浏览器能代理 但是终端并没有完成代理

成功了，3Q

**Comment by bopo** [comment]
在go。mod 文件结尾加以下一段就可以了

replace (
	cloud.google.com/go => github.com/googleapis/google-cloud-go v0.26.0
	golang.org/x/lint => github.com/golang/lint v0.0.0-20180702182130-06c8688daad7
	golang.org/x/net => github.com/golang/net v0.0.0-20181011144130-49bb7cea24b1
	golang.org/x/oauth2 => github.com/golang/oauth2 v0.0.0-20180821212333-d2e6202438be
	golang.org/x/sync => github.com/golang/sync v0.0.0-20180314180146-1d60e4601c6f
	golang.org/x/sys => github.com/golang/sys v0.0.0-20180830151530-49385e6e1522
	golang.org/x/text => github.com/golang/text v0.3.0
	golang.org/x/tools => github.com/golang/tools v0.0.0-20180828015842-6cd1fcedba52
	google.golang.org/appengine => github.com/golang/appengine v1.1.0
	google.golang.org/genproto => github.com/google/go-genproto v0.0.0-20180817151627-c66870c02cf8
	google.golang.org/grpc => github.com/grpc/grpc-go v1.16.0
)

**Comment by tonyboxes** [comment]
感谢各位，master 已经加上。
