### ISSUE TITLE
您好，我在看您的代码，有些结构体不是很清楚，比如Channel.watchOps,您那有相关结构体得说明吗？

### ISSUE THREAD

**Issue by Liangzx** [Terry-Mao/goim#296]
![image](https://user-images.githubusercontent.com/13699123/57498133-3efc4500-730d-11e9-95f6-c3fb4f273a79.png)

**Comment by Junxwan** [comment]
最近刚看完源码 可以参考一下我写的注解或许有帮助
https://github.com/Junxwan/goim

**Comment by Liangzx** [comment]
好的我关注你哈

**Comment by tsingson** [comment]
mid 就是 memberID , 当前 channel ( 用户端与 comet 的长连接) 

watchOps 是一个map 映射表, 其中的 int32 是房间号

watchOps 用来监听当前客户端接收哪个房间的 im 消息推送, 具体细节看测试用例有详细说明


祝愉快.

**Comment by Junxwan** [comment]
mid跟channel关系是一对多(一个人同时看两个以上房间讯息)
key跟channel关系是一对一(针对一个房间的连线)

watchOps好像只会在做mid or broadcast message才会用到，room message就没用到

**Comment by tsingson** [comment]
> mid跟channel关系是一对多(一个人同时看两个以上房间讯息)
> key跟channel关系是一对一(针对一个房间的连线)
> 
> 看redis hash table结构就知道
> 
> watchOps好像只会在做mid or broadcast message才会用到，room message就没用到

查看相关代码中的 data flow , 由 job 发到 channel , 再由 channel ( 中的 ring buffer ) 发送到 TCP / websocket client .............


.

**Comment by lchjczw** [comment]
> 最近刚看完源码，可以参考一下我写的注解(个人理解)或许有帮助
> https://github.com/Junxwan/goim

@Junxwan 你这个图使用什么软件做的，看着不错

**Comment by Junxwan** [comment]
这个 https://www.draw.io/

**Comment by tsingson** [comment]
> 这个 https://www.draw.io/

真用心啊....... 

代码看得多细致多深入, 才能把这么多函数的调用关系画得这么细致.
另外, 数据结构中的链表, map ,  ring buffer 标示也有点个人风格

**Comment by lchjczw** [comment]
@Junxwan 谢谢哈，这两张图画的很好啊，读代码省了一堆的时间

**Comment by Junxwan** [comment]
当初看了1-2个礼拜，图只是简易版的流程，当参考就好
看完代码后会觉得其实更复杂

能帮助到各位更好，就像再看到@tsingson 对于watchOps解释后才知我以前理解错误

**Comment by Liangzx** [comment]
谢谢你们了 @Junxwan @tsingson

**Comment by huangyunbo** [comment]
@Junxwan @tsingson 对于watchOps的理解，理解成房间应该是有偏差的。
1、watchOps = watchOperate的切片，意思是监听操作的意思，而不是watchRooms。
2、里面的NeedPush方法，来判断是否拥有这个Operate，才能推送。
3、Operate刚好和协议里面的Op都是int32，也是操作id的意思。
4、roomid是string类型。
综上所述，应该是当登录成功，每个ch都拥有一组Operate。当广播消息的时候，判断是否监听这个操作，有监听，就推送下去。
当然完全当做房间id来用，也是完全能实现监听其他房间消息的作用，只是从我上面提的1、4这2点来看，不像房间id的意思。

**Comment by tsingson** [comment]
这么老的讨论依然活跃啊............ 

operation 的定义, 来自这里
```
syntax = "proto3";

package goim.comet;
option go_package = "grpc";

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

/*
 * v1.0.0
 * protocol
 */
message Proto {
    int32 ver = 1 [(gogoproto.jsontag) = "ver"];
    int32 op = 2 [(gogoproto.jsontag) = "op"];
    int32 seq = 3 [(gogoproto.jsontag) = "seq"];
    bytes body = 4 [(gogoproto.jsontag) = "body"];
}
```

具体的 operation 值定义在这里 /api/comet/grpc/operation.go
```
package grpc

const (
	// OpHandshake handshake
	OpHandshake = int32(0)
	// OpHandshakeReply handshake reply
	OpHandshakeReply = int32(1)

	// OpHeartbeat heartbeat
	OpHeartbeat = int32(2)
	// OpHeartbeatReply heartbeat reply
	OpHeartbeatReply = int32(3)

	// OpSendMsg send message.
	OpSendMsg = int32(4)
	// OpSendMsgReply  send message reply
	OpSendMsgReply = int32(5)

	// OpDisconnectReply disconnect reply
	OpDisconnectReply = int32(6)

	// OpAuth auth connnect
	OpAuth = int32(7)
	// OpAuthReply auth connect reply
	OpAuthReply = int32(8)

	// OpRaw raw message
	OpRaw = int32(9)

	// OpProtoReady proto ready
	OpProtoReady = int32(10)
	// OpProtoFinish proto finish
	OpProtoFinish = int32(11)

	// OpChangeRoom change room
	OpChangeRoom = int32(12)
	// OpChangeRoomReply change room reply
	OpChangeRoomReply = int32(13)

	// OpSub subscribe operation
	OpSub = int32(14)
	// OpSubReply subscribe operation
	OpSubReply = int32(15)

	// OpUnsub unsubscribe operation
	OpUnsub = int32(16)
	// OpUnsubReply unsubscribe operation reply
	OpUnsubReply = int32(17)
)

```
注意这个 	OpSub = int32(14)

在 channel.go 里 , 这里有个方法定义
```
// Watch watch a operation.
func (c *Channel) Watch(accepts ...int32) {
	c.mutex.Lock()
	for _, op := range accepts {
		c.watchOps[op] = struct{}{}
	}
	c.mutex.Unlock()
}
```

这个 Watch 方法, 在 comet/operation.go 里被引用
这个方法 func (s *Server) Operate........ 用在 comet 服务的 server_tcp.go / server_websocket.go 中能看到详细用法.

```
// Operate operate.
func (s *Server) Operate(ctx context.Context, p *model.Proto, ch *Channel, b *Bucket) error {
	switch p.Op {
	case model.OpChangeRoom:
		if err := b.ChangeRoom(string(p.Body), ch); err != nil {
			log.Errorf("b.ChangeRoom(%s) error(%v)", p.Body, err)
		}
		p.Op = model.OpChangeRoomReply
	case model.OpSub:
		if ops, err := strings.SplitInt32s(string(p.Body), ","); err == nil {
			ch.Watch(ops...)
		}
		p.Op = model.OpSubReply
	case model.OpUnsub:
		if ops, err := strings.SplitInt32s(string(p.Body), ","); err == nil {
			ch.UnWatch(ops...)
		}
		p.Op = model.OpUnsubReply
	default:
		// TODO ack ok&failed
		if err := s.Receive(ctx, ch.Mid, p); err != nil {
			log.Errorf("s.Report(%d) op:%d error(%v)", ch.Mid, p.Op, err)
		}
		p.Body = nil
	}
	return nil
}

```



请注意这句
```
	case model.OpSub:
		if ops, err := strings.SplitInt32s(string(p.Body), ","); err == nil {
			ch.Watch(ops...)
		}
```
明显可见, ops 是从 p.Body 里, 通过 strings.SplitInt32s 对 "xxxx,xxxx,xxxx" 以 "," 拆分并转化为 int32 得到的.

那么, 什么内容以 "xxxx,xxxx,xxxx"  的形式存在 p.Body 里呢???

这个最终的小答案, 就由大家来寻找吧.

至少, 说明了 watchOps 这个 int32 并不是 /api/comet/grpc/operation.go 里定义的 operation 


以上, 祝安康,愉快.

2020/02/20 tsingson 于 深圳.南山.小罗号口琴音乐中心

**Comment by huangyunbo** [comment]
@tsingson 谢谢你的回答。

**Comment by leeyo** [comment]
@tsingson 看了你的回答，还是没有理解作者的真实意图。首先这个 watchOps 的命名容易和 operate 搞混，看上面部分朋友的回答也是把它搞混了。
看 client.js 的实例，看起来像是 room
`var token = '{"mid":123, "room_id":"live://1000", "platform":"web", "accepts":[1000,1001,1002]}'`

看 api.proto，分开定义了，所以排除是  operate

message Proto {
    int32 ver = 1 [(gogoproto.jsontag) = "ver"];
    int32 op = 2 [(gogoproto.jsontag) = "op"];
    int32 seq = 3 [(gogoproto.jsontag) = "seq"];
    bytes body = 4 [(gogoproto.jsontag) = "body"];
}

message Empty{}

message PushMsgReq {
    repeated string keys = 1;
    int32 protoOp = 3;
    Proto proto = 2;
}

假设是 room，这里 room_id  和 accepts 又重复了。从需求端来理解，room和operate都可以，所以还是没有搞清楚这个到底代表什么。

**Comment by sngyai** [comment]
> @tsingson 看了你的回答，还是没有理解作者的真实意图。首先这个 watchOps 的命名容易和 operate 搞混，看上面部分朋友的回答也是把它搞混了。
> 看 client.js 的示例，看起来像是 room。假设是 room，这里 room_id 和 accepts 又重复了
> `var token = '{"mid":123, "room_id":"live://1000", "platform":"web", "accepts":[1000,1001,1002]}'`
> 
> 看 api.proto，分开定义了，所以排除是 operate
> 
> message Proto {
> int32 ver = 1 [(gogoproto.jsontag) = "ver"];
> int32 op = 2 [(gogoproto.jsontag) = "op"];
> int32 seq = 3 [(gogoproto.jsontag) = "seq"];
> bytes body = 4 [(gogoproto.jsontag) = "body"];
> }
> 
> message Empty{}
> 
> message PushMsgReq {
> repeated string keys = 1;
> int32 protoOp = 3;
> Proto proto = 2;
> }
> 
> 你在 May/10 2019 的回答说：
> 
> > watchOps 是一个map 映射表, 其中的 int32 是房间号
> 
> Feb/21 2020 的回答说：
> 
> > watchOps 这里是不是房间呢? 有可能不是...............
> 
> 从需求端来理解，room和operate都可以，所以还是没有搞清楚这个到底代表什么。

应该是订阅吧，主要用在Brodcast广播，PushMsg单播时候也用了；
代码实现上：js example里面的curl命令operation为1000，client连接的时候传了accepts有1000、1001、1002，这里因为1000消息才通的；
逻辑上，用户只能加入一个room，但是可以订阅多个operation；
猜测使用场景是UP主发新动态时候的广播。

**Comment by nextonr** [comment]
@tsingson 请问您在wiki画的架构图用的是什么软件
