### ISSUE TITLE
请问下"discovery://default/goim.logic"这个 地址什么意思啊 看不明白

### ISSUE THREAD

**Issue by HelloWorldZQ** [Terry-Mao/goim#300]
这个 地址什么意思啊 看不明白
![image](https://user-images.githubusercontent.com/10047555/57696494-75c2ba00-7683-11e9-950f-7ed06851f28e.png)

**Comment by Junxwan** [comment]
应该是grpc load balance用的

**Comment by tsingson** [comment]
是 logic 网元的 gRPC 名称, 相当于DNS 中的域名, 用来得到logic 网元 gRPC 服务端的 ip 地址.

**Comment by HelloWorldZQ** [comment]
![image](https://user-images.githubusercontent.com/10047555/57741230-6593f480-76ee-11e9-9d35-58f8397c8c32.png)
ok 明白了应该是这个 地方起作用了
多谢 2位

**Comment by tsingson** [comment]
@HelloWorldZQ  请关闭这个 issue吧 ( 总在我的 github 首页显示着....... 有点强迫症, 想去隐藏掉) 

:)
