### ISSUE TITLE
addr := ip.InternalIP() 这个函数有问题

### ISSUE THREAD

**Issue by HelloWorldZQ** [Terry-Mao/goim#301]
addr := ip.InternalIP() 在存在多个适配器的时候 取不到有效的ip, 添加一个判断 work 了
![image](https://user-images.githubusercontent.com/10047555/57743029-089c3c80-76f6-11e9-9b84-17cad5d90a72.png)

![image](https://user-images.githubusercontent.com/10047555/57742782-14d3ca00-76f5-11e9-86fd-caefab4a0fcf.png)

![image](https://user-images.githubusercontent.com/10047555/57742757-fff73680-76f4-11e9-8300-5e7ca04481eb.png)

**Comment by tonyboxes** [comment]
可以帮提交mr看看不的？

**Comment by HelloWorldZQ** [comment]
please check

**Comment by tonyboxes** [comment]
修复已合并，谢谢
