### ISSUE TITLE
comet 有做流控吗？

### ISSUE THREAD

**Issue by starsea** [Terry-Mao/goim#302]
RT

**Comment by tonyboxes** [comment]
系统可以做open files连接数限制

**Comment by starsea** [comment]
> 系统可以做open files连接数限制

请问下如果auth 失败 返回客户端什么呢

**Comment by tsingson** [comment]
> > 系统可以做open files连接数限制
> 
> 请问下如果auth 失败 返回客户端什么呢

拒绝连接.

**Comment by tonyboxes** [comment]
其实可以考虑返回error operation，对应的错误信息给到客户端。
