### ISSUE TITLE
commet模块长连接channel切换room可能会导致链表出现环路

### ISSUE THREAD

**Issue by listen-lavender** [Terry-Mao/goim#306]
如果业务层在切换room的时候，没有做好判断，走到里面，会造成channel的prev和next产生环路

[代码位置](https://github.com/Terry-Mao/goim/blob/master/internal/comet/bucket.go#L69-L91)

**Comment by iwannay** [comment]
同样遇到了，搞的头大 @listen-lavender

**Comment by iwannay** [comment]
@listen-lavender 你找到解决方案了么？

**Comment by listen-lavender** [comment]
1. 方案一（fork goim代码，在ChangeRoom里面加重复直接返回判断）![fix](https://user-images.githubusercontent.com/4168558/59667543-82d64a00-91e9-11e9-9bfe-e27d5aa6e5b1.png)
2. 方案二（业务代码里面保证ChangeRoom里面当前的room id和切换的目标room id不会相同）

**Comment by listen-lavender** [comment]
@iwannay
