### ISSUE TITLE
快速向websocket 发送数据出现数据乱码， 解析ws 数据出错了，mask给缓冲覆盖？

### ISSUE THREAD

**Issue by jsaaae** [Terry-Mao/goim#315]
if mask {
		maskKey, err = c.r.Pop(4)
		if err != nil {
			return
		}
	}
	// read payload
	if payloadLen > 0 {
		if payload, err = c.r.Pop(int(payloadLen)); err != nil {
			return
		}
		if mask {
			maskBytes(maskKey, 0, payload)
		}
	}

**Comment by tonyboxes** [comment]
单线程处理的，理论上是不会有这个问题的，是怎么进行访问ws的呢

**Comment by sampork** [comment]
最近遇到这个bug，是请求的包体比较大导致的
原因是maskKey是指向c.r里buf的引用，当请求包体比较大无法一次收完时，c.r.Pop(int(payloadLen))会触发fill()继续收包，而fill()收包前会往前挪动buf数据，覆盖已经读取过的，这时maskKey指向的已经读取的buf段会被覆盖，导致值被修改，解决方法就是maskKeyPop出来后拷贝一份

**Comment by jsaaae** [comment]
是的。 mask 要进行深拷贝，不然给后面的数据覆盖了

**Comment by jsaaae** [comment]
> 单线程处理的，理论上是不会有这个问题的，是怎么进行访问ws的呢

正常连接，快速发送就就可以出现了，  发送包弄大一点

**Comment by helloddyl** [comment]
> 单线程处理的，理论上是不会有这个问题的，是怎么进行访问ws的呢

表示也遇到过这样的问题，在deepin上使用flutter的ws出现（几乎百分百），demo却没有问题，不断定位发现也是mask被覆盖，目前我解决方案也是copy出maskkey来避免覆盖的情况发生
