### ISSUE TITLE
运行comet和job一直报错

### ISSUE THREAD

**Issue by hhhero** [Terry-Mao/goim#331]
各位大佬，我在运行comet和job时一直报6172 client.go:551] discovery: client.Get(http://192.168.1.124:7171/discovery/polls?appid=infra.discovery&env=dev&hostname=xiaoniudeMac-mini.local&latest_timestamp=1587103736029933000) error(Get "http://192.168.1.124:7171/discovery/polls?appid=infra.discovery&env=dev&hostname=xiaoniudeMac-mini.local&latest_timestamp=1587103736029933000": context canceled)，怎么解决。恳请大佬帮助

**Comment by PykeChen** [comment]
同，求解答

**Comment by ltstudy** [comment]
怎么解决的？服了这个
