### ISSUE TITLE
建议把kafka的队列改写成通用的接口

### ISSUE THREAD

**Issue by Icedroid** [Terry-Mao/goim#34]
kafka安装还是有点小麻烦，要安装jvm，如果能把队列这块写成通用的接口，可以接入redis、MQ等的队列服务进去，让使用者选择哪个队列服务就再好不过了。谢谢！

**Comment by sumory** [comment]
支持

**Comment by roamdy** [comment]
楼上的说法可以说直接把goim的消息机制重翻了……

**Comment by hyper-carrot** [comment]
+1

**Comment by alex023** [comment]
+1

**Comment by anonzi** [comment]
+1

**Comment by Terry-Mao** [comment]
那么不喜欢Kafka啊

**Comment by hyper-carrot** [comment]
@Terry-Mao 依赖Kafka又要依赖Zk之类的，这一大坨东西如果以前没有就需要额外的资源和成本支持啊。

**Comment by liutaihua** [comment]
不是还有个NSQ是也是纯golang的么

**Comment by Terry-Mao** [comment]
@liutaihua NSQ 是垃圾。

**Comment by tjhyupo505** [comment]
@hyper-carrot 同意你的观点，依赖有点多，要是能更少的话肯定好了，但是看起来这个改动有点大。

**Comment by hyper-carrot** [comment]
@tjhyupo505 我觉得通用化是必要的，可以在社区中发起任务，一步一步来吧

**Comment by webee** [comment]
@Terry-Mao 为什么说NSQ是垃圾，能详细说说吗?

**Comment by liutaihua** [comment]
@Terry-Mao NSQ垃圾求解释＋1，有朋友做im在用它

**Comment by webee** [comment]
@liutaihua 刚看了这个对比http://bravenewgeek.com/dissecting-message-queues/, nsq好像真的不咋样，nats很不错啊。

**Comment by hyper-carrot** [comment]
@webee nats用功能精简的代价来换取性能，就跟zmq速度快但是需要自己做额外工作才能满足要求一样。

**Comment by Terry-Mao** [comment]
结构有大修改，目前暂时会用Kafka为主，多IDC版本最近会上线
