### ISSUE TITLE
logic的grpc文件api.pd.go编译问题

### ISSUE THREAD

**Issue by duteng666** [Terry-Mao/goim#349]
logic的api.proto增加了新的grpc方法 需要重新生成pd.go文件 现在编译就出现：
![图片](https://user-images.githubusercontent.com/28138852/98195014-b5f2b800-1f5b-11eb-835b-44425523a183.png)

求解怎么可以正常编译

**Comment by zxiaofee001** [comment]
这个是不是不维护了？

**Comment by zxiaofee001** [comment]
我也想知道 咋编译

**Comment by djl641043558** [comment]
> 我也想知道咋编译

https://github.com/gogo/protobuf

**Comment by tonybase** [comment]
目前已经去掉了gogo不依赖其它proto
