### ISSUE TITLE
install logic模块时出错

### ISSUE THREAD

**Issue by l603430** [Terry-Mao/goim#35]
你好，在执行到第四步的第二小步，编译logic模块的时候，提示../../../Shopify/sarama/broker.go:78:28: error: reference to undefined identifier ‘tls.DialWithDialer’
    b.conn, b.connErr = tls.DialWithDialer(&dialer, "tcp", b.addr, conf.Net.TLS.Config)........
我怀疑是版本不兼容。能否上传一个depend，方便使用，谢谢

**Comment by Terry-Mao** [comment]
好像是 Shopify/sarama 更新过版本不兼容了，我看下怎么处理

**Comment by l603430** [comment]
能不能用godep save把你本地的依赖上传到github

**Comment by Terry-Mao** [comment]
我先看下兼容新的 kafka client，godep还不熟，等等；

**Comment by thinkboy** [comment]
@l603430 go版本是多少？是否更新到最新Shopify/sarama了？

**Comment by Terry-Mao** [comment]
我们昨天用go 1.5.1 可以编译通过

**Comment by l603430** [comment]
今天使用go1.51安装成功，感谢
