### ISSUE TITLE
建议使用godep（go语言第三方依赖管理）

### ISSUE THREAD

**Issue by jeffbmob** [Terry-Mao/goim#37]
毛总，建议用godep把所有的依赖包都保存到代码里，电脑经常不能google里的代码

**Comment by Terry-Mao** [comment]
额。。。godep 现在是主流依赖管理了么

**Comment by hyper-carrot** [comment]
I recommend glide.

**Comment by cnjack** [comment]
遇到同样的问题，然后去第三方包管理里面直接下载的，ps直接翻墙貌似下不了
gopkg.in算是一个不错的解决方案

**Comment by mysterytree** [comment]
gb

**Comment by Terry-Mao** [comment]
准备上glide了
