### ISSUE TITLE
刚看了新闻，新闻介绍说是纯Golang实现的，为啥依赖废品java环境？

### ISSUE THREAD

**Issue by sgon00** [Terry-Mao/goim#39]
1，新闻介绍纯Golang实现，我在readme，看到要依赖废品java环境？？
2，英文文档连接，点开是404。
3，中文文档连接，标题写的是《gopush-cluster》，是不是标题应该改一下？

**Comment by Terry-Mao** [comment]
文档还在完善中。。。

**Comment by Terry-Mao** [comment]
依赖了Kafka

**Comment by Terry-Mao** [comment]
@thinkboy

**Comment by sgon00** [comment]
我对Kafka不太了解，标题有点唐突了。Sorry。感谢您的快速回复。

**Comment by Terry-Mao** [comment]
Kafka 是吞吐非常优秀的队列
