### ISSUE TITLE
install comet的时候报错

### ISSUE THREAD

**Issue by TomShine** [Terry-Mao/goim#41]
![image](https://cloud.githubusercontent.com/assets/3054443/11451186/42310a22-95f7-11e5-9650-22d5c21e986f.png)

**go install** comet的时候报的错，我自己也看了**ring.go**，确实没有那个**InitRing**的函数

ps：对了您能不能把那个日志库换了，或者把他放到这个项目里面，没有VPN的linux下不来那个log库

**Comment by Terry-Mao** [comment]
fix 了，之前修复另外一个问题，忘记改了这里

**Comment by Terry-Mao** [comment]
依赖的问题，我尽快看下怎么搞，或者镜像一个，我先看看大家推荐的godeps
