### ISSUE TITLE
comet <-> logic 通讯替换protorpc

### ISSUE THREAD

**Issue by Terry-Mao** [Terry-Mao/goim#43]
protorpc 参数和返回都是小对象，容易对GC产生压力，因为connect 和 disconnect 参数比较固定，使用tcp + package 方式发送包，使用值拷贝方式替换对象

comet 消息推送也是类似问题，comet 因为连接密集+内存密集，GC需要很严谨，
对于 logic 和router 以及 job 会相对还好

**Comment by gbember** [comment]
protorpc感觉不直观  还是grpc好

**Comment by Terry-Mao** [comment]
已经更新回net/rpc，目前通讯还不是最大瓶颈，之后考虑
