### ISSUE TITLE
comet和logic之间是http通讯还是也是长连接？

### ISSUE THREAD

**Issue by 879913935** [Terry-Mao/goim#44]

**Comment by Terry-Mao** [comment]
对，使用的我们基于net/rpc 改版的 protorpc 参考 github.com/Terry-Mao/protorpc，目前这块还会进一步优化。

**Comment by 879913935** [comment]
如果我要扩容，比如增加了comet机器，logic是自动会发现新增的并连接上，还是说logic层会有一个comet机器列表的类似配置，启动的时候全部分别建立个连接。

**Comment by Terry-Mao** [comment]
是comet 主动连接的logic，不是logic 连接comet。。。comet连接logic 可以是用lvs 4层负载来做

**Comment by Terry-Mao** [comment]
所以comet 启动以后，只需要知道logic的 单个VIP

**Comment by 879913935** [comment]
嗯，comet和logic都是无状态的，理解你的意思哈，那比如cometA上的用户给cometB上的用户发了一个消息给logic，logic怎么转发给cometB的呀

**Comment by Terry-Mao** [comment]
目前的流程是，cometA 把这个消息转发给logic，logic查询路由服务（router）然后把这个推送任务异步发送给Kafka，Job服务从Kafka消费，推送给cometB，目前A,B comet 可能夸机房

在未来 即将支持，router的多IDC复制，因此查询router变成local IDC query

**Comment by 879913935** [comment]
嗯我是确实对golang代码不熟悉。只能看些配置文件知道一些，我看你job里的配置文件里列出了comet列表，是不是在comet增加的时候，job服务也需要重启或者有某种策略更新配置之类的。

还有个消息存储方面的，现在其实是没有持久化的好像，如果要是持久化。您觉得选型方面是mysql还是redis这种比较合适，就是参考下您的建议，然后这个存储的处理放在哪里处理比较好，是独立出一个消息持久化服务，从MQ读取并存储，但是不太确定MQ好像有的不支持重复消费吧，就是JOB消费过就没了。

还有个数据统计方面的，就是我要监控，或者拦截，统计各种消息数量之类的，在哪做比较优雅。耦合小，性能损耗低

我是不是问题太多啦~~谢谢哈

**Comment by Terry-Mao** [comment]
目前comet新增，job 是需要重启的，这个以后可以做成服务发现，不过目前job重启还好，因为消息都在kafka里面，可以随时重启，比较方便，你说的这个是一个运维优化的点，多谢。

消息存储，我看Facebook 是使用的HBase，目前来看场景比较合适，缓存可以用mc和redis组合，mc负责kv，redis 负责列表，存储我建议是异步化，都从kafka抽取一份数据来转存，利用kafka pub/sub group的特性来实现

数据统计的话 最简单是植入代码在代码中统计，要么就是离线利用日志来计算，我建议是日志来做比较合适，代码侵入比较少

**Comment by 879913935** [comment]
万分感谢，我再自己梳理下。

**Comment by Terry-Mao** [comment]
：）
