### ISSUE TITLE
现在支持集群吗？

### ISSUE THREAD

**Issue by ustime** [Terry-Mao/goim#5]
好像没看到集群的功能啊

**Comment by Terry-Mao** [comment]
goim 的 comet模块只是一个接入层，接入层的集群实现，有很多方案，我举两个点：

**Comment by liudanking** [comment]
comet多节点以后，如果用户A连接comet 1，用户B连接comet 2，用户A、B怎么互发消息呢？通过router层来路由发现？

**Comment by Terry-Mao** [comment]
通过路由来中转发现
