### ISSUE TITLE
delete map操作是否重复？

### ISSUE THREAD

**Issue by it-man-cn** [Terry-Mao/goim#51]
下面代码的delete map操作是否重复了？还是出于什么考虑？
https://github.com/Terry-Mao/goim/blob/master/router/cleaner.go#L82
func (c *Cleaner) remove(key int64) {
	if e, ok := c.maps[key]; ok {
		delete(c.maps, key)
		e.prev.next = e.next
		e.next.prev = e.prev
		e.next = nil // avoid memory leaks
		e.prev = nil // avoid memory leaks
		c.size--
	}
}
https://github.com/Terry-Mao/goim/blob/master/router/cleaner.go#L102
for i = 0; i < maxCleanNum; i++ {
		if e = c.back(); e != nil {
			if e.expire() {
				c.remove(e.Key)
				delete(c.maps, e.Key)
				keys = append(keys, e.Key)
				continue
			}
		}
		break
	}

**Comment by Terry-Mao** [comment]
应该是个bug，我再细看下

**Comment by Terry-Mao** [comment]
@thinkboy 看下这个问题？

**Comment by Terry-Mao** [comment]
#68 fix
