### ISSUE TITLE
复用推送模块的可能性

### ISSUE THREAD

**Issue by Stan-Wang** [Terry-Mao/goim#6]
最近也在做推送和IM相关的优化和重构，考虑将推送作为基础模块支撑IM的运作。将上行下行消息逻辑分开处理，上行消息使用短连接发至IM逻辑处理API,下行消息通过推送服务直达客户端。GoIM有相关的重构需求么？

**Comment by Terry-Mao** [comment]
目前已经是你说的样子，goim中的comet部分就是连接的基础部分，你看下comet中的operator.go就是把逻辑抽象成了接口，让使用者自己实现。comet只是负责消息的转发和推送

**Comment by Stan-Wang** [comment]
我是指基于服务模块的支撑，即goim没有comet模块，调用gopush-cluster实现消息的下发，只有处理消息上行的api模块（类似于gopush-cluster中的web）。

**Comment by Terry-Mao** [comment]
上行还是会走comet，因为涉及到消息加密解密，以及报文的支持，之前是纯下发的。而且comet和之前的gopush-cluster的comet 做了不少优化。。
