### ISSUE TITLE
里面的四个模块有没有单独的文档

### ISSUE THREAD

**Issue by catchSora** [Terry-Mao/goim#69]
我看了一个礼拜还是不明白模块之间数据是怎么交互的, 远程调用倒是看明白了, 但tcp长连接建立后, 用户信息和server是怎么保存到router的

**Comment by Terry-Mao** [comment]
comet -> logic -> router，大概是这样的走向。

**Comment by Terry-Mao** [comment]
@thinkboy 文档帮多加一些？

**Comment by ieworks** [comment]
@catchSora 我差不多也看了一周了，job 的启动也一直报错. @thinkboy 必要的文档对新手还是很有意义的，忘添加一些。
