### ISSUE TITLE
aes解密复用cipher.BlockMode多次解密数据出错的问题

### ISSUE THREAD

**Issue by 2bwithu** [Terry-Mao/goim#7]
aes解密复用cipher.BlockMode多次解密数据出错的问题，仅第一次正确，后面iv发生变化

**Comment by Terry-Mao** [comment]
因为AES对称加密是流式的，所以客户端和服务端必须一直使用同一个cbcencryptor 和 cbcDecryptor，不能每次都new，iv会在加密以后产生变化，以供下次解密使用
