### ISSUE TITLE
romet模块room broadcast在websocket协议下有个可能会导致proto body空

### ISSUE THREAD

**Issue by liutaihua** [Terry-Mao/goim#72]
在dispatchWebsocket时，显示的 p.Body = nil，看注释avoid memory leak
不过proto在Channel里是用指针传递的， 
这里的p.Body = nil， 在一个房间大量channel并发的时候，会导致其他连接得到的是一个空的Body

目前我看到空的消息产生是这样的， 注释这里之后恢复正常。

**Comment by Terry-Mao** [comment]
这个确实是bug，tcp竟然是没有的，多谢，我们fix下，另外websocket和tcp的协议兼容，你有什么好的意见。websocket的bug，应该是我们大意了，我们线上全部是tcp的，websocket测试比较少，多谢反馈

**Comment by Terry-Mao** [comment]
https://github.com/Terry-Mao/goim/commit/f4fb0deb1d600df5cac41c4cc11da7cd6af5cbfb#diff-99b62f441b330b28349a7bf2def166d8L201

**Comment by liutaihua** [comment]
tcp是因为有writer buffer， 所以木有这个问题吧。
ws和tcp兼容的问题， 可否底下都走一次tcp那边的逻辑， ws只当一个外层的接入。 ws的消息从tcp那边逻辑获取，绕了一层＝。＝
