### ISSUE TITLE
遇到一个奔溃，不知道是不是我的问题，希望高人指教

### ISSUE THREAD

**Issue by chance1254** [Terry-Mao/goim#83]
根据文档配置完成也跑了起来，不过用客户端demo跑了一下再收到第一个心跳之后服务器端就会崩掉，错误信息如下：
[EROR] key:  handshake failed error(default server codec pack length error)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40a11f]

goroutine 33209 [running]:
panic(0x8823a0, 0xc8200100f0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
main.LogSlow(0x917c40, 0x6, 0xc820133908, 0x3, 0x0)
	/root/workspace/golang/src/goim/comet/slow.go:50 +0x55f
main.(*Server).dispatchTCP(0xc8255cb8f0, 0xc820133908, 0x3, 0xc820026280, 0xc820056ad8, 0xc848dec000, 0xc8491f6000, 0xc820056a90)
	/root/workspace/golang/src/goim/comet/tcp.go:221 +0xa22
created by main.(*Server).serveTCP
	/root/workspace/golang/src/goim/comet/tcp.go:132 +0x8e6
不知道是不是我配置的有问题

**Comment by weisd** [comment]
最新的版本问题挺多啊，我回退到加slow之前的版本了

**Comment by Terry-Mao** [comment]
已经删除了slowlog，线上遇到一些性能问题、
