### ISSUE TITLE
客户端连接时如何指定自己的uid？

### ISSUE THREAD

**Issue by DongweiLee** [Terry-Mao/goim#89]
抱歉把github的Issuse的当提问地了，但该项目网上能查的文档真的太少了

我现在用python模仿了web客户端，建起了连接；
当我要给该客户端推送消息时，首先需要知道该连接的uid
请问我该如何获取此连接的uid呢？或者允许我在建立连接时的请求时指定？
烦请作者解惑

**Comment by weisd** [comment]
comet连接调了logic的Connect方法，里面调了auther.Auth作验证并返回uid, roomid
你可以修改原logic/auth.go， 或自己实现一个Auther

**Comment by Terry-Mao** [comment]
是的，需要自己实现，因为涉及到自己的业务逻辑，所以留了一个auth。go 自己实现
