### ISSUE TITLE
goim 是否适合用于即时通讯的消息系统呢？

### ISSUE THREAD

**Issue by ieworks** [Terry-Mao/goim#91]
client 发送消息
1 client->comet->logic->router 
2 caller->logic->kafa->job->client
这两个消息链没有直接联系起来，所以在场景 clientA 发送 消息到 clientB 时，要再次通过 caller 来 push消息。 这样来看，goim 主要是使用场景应该是 push 消息到多个客户端。但是这样有一点，我还没有理解这里的 router 这个角色发挥了什么样的作用呢？

**Comment by Terry-Mao** [comment]
router 主要记录了 一个用户 属于 哪个server，你可以认为是路由表吧

至于 2 这个问题，caller 可以是 http 接口过来的，也可以是 goim comet的角色，你看下其实协议是保留了指令实现，也就是说，caller 可以是comet 自身的
