### ISSUE TITLE
memory leak with the Closure

### ISSUE THREAD

**Issue by liutaihua** [Terry-Mao/goim#92]
websocket下有一处内存泄露，跟了一下pprof应该是在做ws close的时候：
	trd = tr.Add(server.Options.HandshakeTimeout, func() {
		conn.Close()
	})
我觉得此处的闭包会导致conn指针被store， gc的时候会漏掉这里， 随着连接不断建立，断开。 pprof里显示ws使用的内存只增不减， 而且都集中在websocket.newConn，
哦对，我这边使用gorilla/websocket替代了golang.org/x/net/websocket

对比测试针对trd做一次fn reset后gc能正确的回收了。
待我线上确定。我放个pr, 只有简单几行

看tcp的代码， 应该一样会有这个问题，不知道是否有人遇到过.

**Comment by Terry-Mao** [comment]
已经fix，谢谢，最近太忙了，好久没上来看了
