### ISSUE TITLE
问下是否能提供容器版goim

### ISSUE THREAD

**Issue by mysterytree** [Terry-Mao/goim#96]
docker启动比较方便

**Comment by Terry-Mao** [comment]
目前还不太熟悉docker，你可以提供一个：）

**Comment by mysterytree** [comment]
@Terry-Mao 
先调研 生产环境肯定是要容器化的  
如果顺利就贡献出来

**Comment by im-qq** [comment]
@mysterytree 你们这块有没有用docker啊

**Comment by mysterytree** [comment]
@im-qq 并没有 我们后来选了另外的方案  另外你这名字有点6
