### ISSUE TITLE
请问，测试中有客户端推送消息，但客户端如何获取消息？即怎么使用

### ISSUE THREAD

**Issue by eric-hon** [Terry-Mao/goim#97]
请问，测试中有客户端推送消息，但客户端如何获取消息？
有没有比较完整的文档，谢谢？
可发我邮箱 eric_hon@126.com

**Comment by Terry-Mao** [comment]
获取消息在bechmark 目录压测有demo可以参考；

**Comment by eric-hon** [comment]
嗯，不过也就看到client里面有读取消息的地方，其他地方都是push
