### ISSUE TITLE
使用java sdk和benchmark/client进行测试是comet TCP出错，跪求解决

### ISSUE THREAD

**Issue by eric-hon** [Terry-Mao/goim#99]
使用java sdk和benchmark/client进行测试是comet TCP出错:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40a0ee]

goroutine 33205 [running]:
main.LogSlow(0x898900, 0x6, 0xc82033d9b0, 0x4, 0x0)
        /home/eric/go/src/goim/comet/slow.go:50 +0x55e
main.(*Server).dispatchTCP(0xc82575d8f0, 0xc82033d9b0, 0x4, 0xc82002c2f0, 0xc82005bbe8, 0xc848f38258, 0xc84cfba000, 0xc82005bba0)
        /home/eric/go/src/goim/comet/tcp.go:221 +0xa00
created by main.(*Server).serveTCP
        /home/eric/go/src/goim/comet/tcp.go:132 +0x8ec

goroutine 1 [chan receive]:
main.InitSignal()
        /home/eric/go/src/goim/comet/signal.go:16 +0x38c
main.main()
        /home/eric/go/src/goim/comet/main.go:91 +0xb39

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

**Comment by weisd** [comment]
go get -u github.com/Terry-Mao/goim

**Comment by Terry-Mao** [comment]
不知道解决没有？

**Comment by eric-hon** [comment]
解决了，为啥直接下载的不行，非得用go get -u github.com/Terry-Mao/goim
谢谢！

**Comment by Terry-Mao** [comment]
额。。。估计没下到最新的
